<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <Title>AL.Data</Title>
        <Description>Data library for the ALClientCS project. Contains data objects equivalent to GData/data.js.</Description>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\AL.Core\AL.Core.csproj"/>
    </ItemGroup>

</Project>
