using System.Linq;
using AL.APIClient.Model;
using AL.Core.Extensions;
using AL.Core.Geometry;
using AL.SocketClient.SocketModel;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Newtonsoft.Json;

namespace AL.Tests.SocketClient.Tests
{
    [TestClass]
    public class JsonConverterTests
    {
        [TestMethod]
        public void DeserializeAchievementProgressDataTest()
        {
            const string ACHIEVEMENT_PROGRESS_DATA = @"{
   ""name"":""firehazard"",
   ""count"":""25"",
   ""needed"":""19975""
}";

            var obj = JsonConvert.DeserializeObject<AchievementProgressData>(ACHIEVEMENT_PROGRESS_DATA);

            Assert.IsNotNull(obj);
        }

        [TestMethod]
        public void DeserializeActionDataTest()
        {
            const string ACTION_DATA = @"{
   ""attacker"":""2144160"",
   ""target"":""Moneybaggers"",
   ""type"":""attack"",
   ""source"":""attack"",
   ""x"":595.7417319170224,
   ""y"":1091.179435638155,
   ""eta"":400,
   ""m"":361,
   ""pid"":""wMhQBT"",
   ""projectile"":""stone"",
   ""damage"":25
}";

            var obj = JsonConvert.DeserializeObject<ActionData>(ACTION_DATA);

            Assert.IsNotNull(obj);
        }

        [TestMethod]
        public void DeserializeCharacterDataTest()
        {
            const string CHARACTER_DATA = @"{
   ""hp"":7826,
   ""max_hp"":7826,
   ""mp"":2020,
   ""max_mp"":2060,
   ""xp"":10375841,
   ""attack"":310,
   ""frequency"":0.670161149825784,
   ""speed"":75,
   ""range"":32,
   ""armor"":141,
   ""resistance"":221,
   ""level"":54,
   ""rip"":false,
   ""afk"":false,
   ""s"":{
      ""mluck"":{
         ""ms"":1484195,
         ""f"":""Dinger""
      }
   },
   ""c"":{
      
   },
   ""q"":{
      
   },
   ""age"":69,
   ""pdps"":0,
   ""id"":""sichi"",
   ""x"":40.40316655490353,
   ""y"":541.1426134776386,
   ""cid"":2,
   ""stand"":false,
   ""skin"":""sarmor2c"",
   ""cx"":{
      ""hat"":""hat322""
   },
   ""slots"":{
      ""ring1"":{
         ""name"":""vitring"",
         ""level"":3
      },
      ""ring2"":{
         ""name"":""ringsj"",
         ""level"":3
      },
      ""earring1"":{
         ""level"":0,
         ""name"":""vitearring""
      },
      ""earring2"":{
         ""name"":""vitearring"",
         ""level"":1
      },
      ""belt"":{
         ""level"":0,
         ""m"":""Chonk003"",
         ""name"":""hpbelt""
      },
      ""mainhand"":{
         ""name"":""carrotsword"",
         ""level"":7
      },
      ""offhand"":null,
      ""helmet"":{
         ""stat_type"":""vit"",
         ""name"":""eears"",
         ""level"":7
      },
      ""chest"":{
         ""level"":7,
         ""stat_type"":""vit"",
         ""name"":""epyjamas""
      },
      ""pants"":{
         ""level"":3,
         ""stat_type"":""vit"",
         ""name"":""wbreeches""
      },
      ""shoes"":{
         ""level"":8,
         ""stat_type"":""vit"",
         ""name"":""eslippers""
      },
      ""gloves"":{
         ""level"":7,
         ""stat_type"":""vit"",
         ""name"":""wgloves""
      },
      ""amulet"":{
         ""level"":6,
         ""name"":""warmscarf""
      },
      ""orb"":{
         ""level"":0,
         ""name"":""test_orb""
      },
      ""elixir"":null,
      ""cape"":{
         ""level"":5,
         ""stat_type"":""vit"",
         ""name"":""angelwings""
      },
      ""trade1"":null,
      ""trade2"":null,
      ""trade3"":null,
      ""trade4"":{
         ""name"":""staff"",
         ""price"":40000000,
         ""rid"":""TfCh"",
         ""level"":9
      }
   },
   ""ctype"":""merchant"",
   ""owner"":""6000633860063232"",
   ""int"":90,
   ""str"":19,
   ""dex"":52,
   ""vit"":89,
   ""for"":3,
   ""mp_cost"":65,
   ""mp_reduction"":20,
   ""max_xp"":13000000,
   ""goldm"":1.01,
   ""xpm"":1.01,
   ""luckm"":1.17,
   ""map"":""main"",
   ""in"":""main"",
   ""isize"":42,
   ""esize"":26,
   ""gold"":37500000,
   ""cash"":427,
   ""targets"":0,
   ""m"":0,
   ""evasion"":4.45,
   ""miss"":0,
   ""reflection"":0,
   ""lifesteal"":0,
   ""manasteal"":0,
   ""rpiercing"":13,
   ""apiercing"":13,
   ""crit"":0,
   ""critdamage"":0,
   ""dreturn"":0,
   ""tax"":0.03,
   ""xrange"":25,
   ""pnresistance"":0,
   ""firesistance"":20,
   ""fzresistance"":20,
   ""stun"":0,
   ""blast"":0,
   ""explosion"":0,
   ""courage"":1,
   ""mcourage"":0,
   ""pcourage"":0,
   ""fear"":0,
   ""items"":[
      {
         ""name"":""stand0""
      },
      {
         ""name"":""blade"",
         ""level"":0
      },
      {
         ""q"":42,
         ""name"":""gemfragment""
      },
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      {
         ""q"":50,
         ""name"":""cscroll0""
      },
      {
         ""q"":26,
         ""name"":""cscroll1""
      },
      null,
      null,
      null,
      null,
      null,
      {
         ""q"":50,
         ""name"":""scroll0""
      },
      {
         ""q"":25,
         ""name"":""scroll1""
      },
      {
         ""q"":16,
         ""name"":""scroll2""
      },
      {
         ""name"":""tracker""
      },
      null,
      null,
      null,
      {
         ""q"":151,
         ""name"":""intscroll""
      },
      {
         ""q"":50,
         ""name"":""dexscroll""
      },
      {
         ""q"":62,
         ""name"":""strscroll""
      },
      {
         ""q"":9000,
         ""name"":""mpot0""
      },
      {
         ""q"":9000,
         ""name"":""hpot0""
      },
      {
         ""q"":9000,
         ""name"":""hpot1""
      },
      {
         ""q"":9000,
         ""name"":""mpot1""
      }
   ],
   ""cc"":1
}";

            var obj = JsonConvert.DeserializeObject<CharacterData>(CHARACTER_DATA);

            Assert.IsNotNull(obj);
        }

        [TestMethod]
        public void DeserializeChestOpenedDataTest()
        {
            const string CHEST_OPENED_DATA = @"{
   ""id"":""lUHVxKFHEl85OVZf5weJNBii0pip9x"",
   ""goldm"":1.01,
   ""opener"":""makiz"",
   ""items"":[
      {
         ""name"":""ringsj"",
         ""level"":0,
         ""looter"":""makiz""
      },
      {
         ""name"":""seashell"",
         ""q"":1,
         ""looter"":""makiz""
      }
   ],
   ""gold"":1655
}";

            var obj = JsonConvert.DeserializeObject<ChestOpenedData>(CHEST_OPENED_DATA);

            Assert.IsNotNull(obj);
        }

        [TestMethod]
        public void DeserializeCorrectionDataTest()
        {
            const string CORRECTION_DATA = @"{
   ""x"":64.123,
   ""y"":792.456,
}";

            var obj = JsonConvert.DeserializeObject<CorrectionData>(CORRECTION_DATA);

            Assert.IsNotNull(obj);
            Assert.IsTrue(new Point(64.123f, 792.456f).Distance(obj) < 10);
        }

        [TestMethod]
        public void DeserializeDeathDataTest()
        {
            const string DEATH_DATA = @"{
   ""id"":""43923109""
}";

            var obj = JsonConvert.DeserializeObject<DeathData>(DEATH_DATA);

            Assert.IsNotNull(obj);
        }

        [TestMethod]
        public void DeserializeDisappearDataTest()
        {
            const string DISAPPEAR_DATA = @"{
   ""id"":""CeeNote"",
   ""reason"":""transport"",
   ""s"":1
}";

            const string DISAPPEAR_DATA2 = @"{
   ""id"":""CeeNote"",
   ""reason"":""transport"",
   ""s"":[5, 10, 1]
}";

            var obj = JsonConvert.DeserializeObject<DisappearData>(DISAPPEAR_DATA);
            var obj2 = JsonConvert.DeserializeObject<DisappearData>(DISAPPEAR_DATA2);

            Assert.IsNotNull(obj);
            Assert.IsNotNull(obj2);
        }

        [TestMethod]
        public void DeserializeDisappearingTextData()
        {
            const string DISAPPEARING_TEXT_DATA = @"{
   ""message"":""+100"",
   ""x"":15.280000219733335,
   ""y"":-413.5399998351999,
   ""id"":""Ploob"",
   ""args"":{
      ""c"":""#006AA9"",
      ""s"":""mp""
   }
}";

            var obj = JsonConvert.DeserializeObject<DisappearingTextData>(DISAPPEARING_TEXT_DATA);

            Assert.IsNotNull(obj);
        }

        [TestMethod]
        public void DeserializeDropDataTest()
        {
            const string DROP_DATA = @"{
   ""x"":64,
   ""y"":792,
   ""items"":0,
   ""chest"":""chest3"",
   ""id"":""pcgm7Iavbtug7zO8xQoumIXaIVFZPL"",
   ""map"":""main""
}";

            var obj = JsonConvert.DeserializeObject<DropData>(DROP_DATA);

            Assert.IsNotNull(obj);
        }

        [TestMethod]
        public void DeserializeEntitiesDataTest()
        {
           const string ENTITIES_DATA = @"{
        ""players"": [
            {
                ""hp"": 5245,
                ""max_hp"": 5271,
                ""mp"": 1885,
                ""max_mp"": 1885,
                ""xp"": 15962472,
                ""attack"": 48,
                ""frequency"": 0.6679415892373209,
                ""speed"": 72,
                ""range"": 20,
                ""armor"": 54,
                ""resistance"": 119,
                ""level"": 56,
                ""party"": ""MrDeePs"",
                ""rip"": false,
                ""code"": true,
                ""afk"": true,
                ""target"": null,
                ""focus"": ""kouin"",
                ""s"": {},
                ""c"": {},
                ""q"": {},
                ""age"": 338,
                ""pdps"": 17.218536885677565,
                ""id"": ""Moneybaggers"",
                ""x"": 412.4300917824425,
                ""y"": 991.1029095899681,
                ""moving"": true,
                ""going_x"": 211,
                ""going_y"": 876,
                ""abs"": false,
                ""move_num"": 17329060,
                ""angle"": -150.2551187030578,
                ""cid"": 7822,
                ""stand"": false,
                ""skin"": ""marmor12a"",
                ""cx"": {
                    ""hair"": ""hairdo520"",
                    ""head"": ""fmakeup01"",
                    ""hat"": ""hat404""
                },
                ""slots"": {
                    ""ring1"": {
                        ""name"": ""vitring"",
                        ""level"": 0
                    },
                    ""ring2"": {
                        ""level"": 3,
                        ""name"": ""vitring""
                    },
                    ""earring1"": {
                        ""name"": ""vitearring"",
                        ""level"": 0
                    },
                    ""earring2"": null,
                    ""belt"": {
                        ""name"": ""hpbelt"",
                        ""level"": 4
                    },
                    ""mainhand"": null,
                    ""offhand"": null,
                    ""helmet"": {
                        ""name"": ""helmet"",
                        ""gift"": 1,
                        ""level"": 0
                    },
                    ""chest"": null,
                    ""pants"": null,
                    ""shoes"": {
                        ""stat_type"": ""dex"",
                        ""name"": ""shoes"",
                        ""level"": 7
                    },
                    ""gloves"": null,
                    ""amulet"": {
                        ""name"": ""hpamulet"",
                        ""level"": 4
                    },
                    ""orb"": {
                        ""name"": ""test_orb"",
                        ""level"": 0
                    },
                    ""elixir"": null,
                    ""cape"": null,
                    ""trade1"": null,
                    ""trade2"": null,
                    ""trade3"": null,
                    ""trade4"": null
                },
                ""ctype"": ""merchant"",
                ""owner"": ""6314512450322432""
            }
        ],
        ""monsters"": [
            {
               ""speed"":25.92,
               ""hp"":85016,
               ""mp"":96,
               ""attack"":640,
               ""xp"":131200,
               ""frequency"":1.072,
               ""max_hp"":86400,
               ""id"":""1869105"",
               ""x"":335.4667740677073,
               ""y"":-2011.3367167663876,
               ""moving"":true,
               ""going_x"":363.95981679423096,
               ""going_y"":-1874.8896953933113,
               ""abs"":false,
               ""move_num"":22612448,
               ""angle"":78.20491891313337,
               ""type"":""wolfie"",
               ""cid"":8,
               ""s"":{
                  
               },
               ""level"":8
            },
            {
               ""speed"":53.92,
               ""hp"":85092,
               ""mp"":96,
               ""attack"":640,
               ""xp"":131200,
               ""frequency"":1.072,
               ""max_hp"":86400,
               ""id"":""1869147"",
               ""x"":253.47654407885798,
               ""y"":-1916.635392105144,
               ""moving"":true,
               ""going_x"":232,
               ""going_y"":-1888,
               ""abs"":false,
               ""move_num"":22612446,
               ""angle"":126.86989764584402,
               ""type"":""wolfie"",
               ""cid"":10,
               ""target"":""makiz"",
               ""s"":{
                  
               },
               ""level"":8
            }
         ],
        ""type"": ""xy"",
        ""in"": ""main"",
        ""map"": ""main""
    }";

            var obj = JsonConvert.DeserializeObject<EntitiesData>(ENTITIES_DATA);

            Assert.IsNotNull(obj);
            Assert.IsTrue(obj.Players.Any());
            Assert.IsTrue(obj.Monsters.Any());
        }

        [TestMethod]
        public void DeserializeEvalDataTest()
        {
            const string EVAL_DATA = @"{
   ""code"":""skill_timeout('attack',1096.1809388171202)""
}";

            var obj = JsonConvert.DeserializeObject<EvalData>(EVAL_DATA);

            Assert.IsNotNull(obj);
        }

        [TestMethod]
        public void DeserializeEventAndBossDataTest()
        {
            const string EVENT_AND_BOSS_DATA = @"{
   ""icegolem"":{
      ""live"":true,
      ""map"":""winterland"",
      ""hp"":16000000,
      ""max_hp"":16000000,
      ""x"":808.9124940370274,
      ""y"":407.6040564394661
   },
   ""snowman"":{
      ""live"":true,
      ""map"":""winterland"",
      ""hp"":1200,
      ""max_hp"":1200,
      ""x"":1111.7317564125299,
      ""y"":-785.8382420118533
   },
   ""franky"":{
      ""live"":true,
      ""map"":""level2w"",
      ""hp"":120000000,
      ""max_hp"":120000000,
      ""x"":-278.0075274742135,
      ""y"":187.81118535586882
   }
}";

            var obj = JsonConvert.DeserializeObject<EventAndBossData>(EVENT_AND_BOSS_DATA);

            Assert.IsNotNull(obj);
        }

        [TestMethod]
        public void DeserializeGameLogDataTest()
        {
            const string GAME_LOG_DATA = "\"Stored 37,500,711 gold\"";

            var obj = JsonConvert.DeserializeObject<string>(GAME_LOG_DATA);

            Assert.AreEqual("Stored 37,500,711 gold", obj);
        }

        [TestMethod]
        public void DeserializeGameResponseDataTest()
        {
            const string STRING_GAME_RESPONSE_DATA = @"""ex_condition""";

            const string GAME_RESPONSE_DATA = @"{
   ""response"":""ex_condition"",
   ""name"":""charging""
}";

            var obj = JsonConvert.DeserializeObject<GameResponseData>(GAME_RESPONSE_DATA);
            Assert.IsNotNull(obj);
            Assert.IsNotNull(obj.Name);
            obj = JsonConvert.DeserializeObject<GameResponseData>(STRING_GAME_RESPONSE_DATA);
            Assert.IsNotNull(obj);
        }

        [TestMethod]
        public void DeserializeHitDataTest()
        {
            const string HIT_DATA = @"{
   ""attacker"":""2144160"",
   ""target"":""Moneybaggers"",
   ""type"":""attack"",
   ""source"":""attack"",
   ""x"":595.7417319170224,
   ""y"":1091.179435638155,
   ""eta"":400,
   ""m"":361,
   ""pid"":""wMhQBT"",
   ""projectile"":""stone"",
   ""damage"":25
}";

            var obj = JsonConvert.DeserializeObject<HitData>(HIT_DATA);

            Assert.IsNotNull(obj);
        }

        [TestMethod]
        public void DeserializeInviteDataTest()
        {
            const string INVITE_DATA = @"{
   ""name"":""earthMer""
}";

            var obj = JsonConvert.DeserializeObject<InviteData>(INVITE_DATA);

            Assert.IsNotNull(obj);
        }

        [TestMethod]
        public void DeserializeNewMapDataTest()
        {
            const string NEW_MAP_DATA = @"{
   ""name"":""bank"",
   ""in"":""bank"",
   ""x"":0,
   ""y"":-37,
   ""direction"":3,
   ""effect"":0,
   ""info"":{
      
   },
   ""m"":1,
   ""entities"":{
      ""players"":[
         {
            ""hp"":7618,
            ""max_hp"":7618,
            ""mp"":4003,
            ""max_mp"":4445,
            ""xp"":391935615,
            ""attack"":123,
            ""frequency"":1.074238046844754,
            ""speed"":86,
            ""range"":25,
            ""armor"":167,
            ""resistance"":471,
            ""level"":76,
            ""rip"":false,
            ""code"":false,
            ""afk"":false,
            ""s"":{
               
            },
            ""c"":{
               
            },
            ""q"":{
               
            },
            ""age"":833,
            ""pdps"":0.002169416492913066,
            ""id"":""CeeNote"",
            ""x"":0,
            ""y"":-328.2299951754007,
            ""moving"":false,
            ""going_x"":0,
            ""going_y"":-328.2299951754007,
            ""abs"":false,
            ""move_num"":17365217,
            ""angle"":-90,
            ""cid"":1161,
            ""stand"":false,
            ""skin"":""marmor2g"",
            ""cx"":{
               ""hair"":""hairdo417"",
               ""head"":""mmakeup00""
            },
            ""slots"":{
               ""ring1"":{
                  ""l"":""l"",
                  ""name"":""ringsj"",
                  ""level"":4
               },
               ""ring2"":{
                  ""name"":""ringsj"",
                  ""level"":4
               },
               ""earring1"":{
                  ""name"":""intearring"",
                  ""level"":4
               },
               ""earring2"":{
                  ""name"":""vitearring"",
                  ""level"":3,
                  ""l"":""l""
               },
               ""belt"":{
                  ""name"":""santasbelt"",
                  ""level"":3
               },
               ""mainhand"":null,
               ""offhand"":null,
               ""helmet"":{
                  ""name"":""eears"",
                  ""level"":9
               },
               ""chest"":{
                  ""level"":9,
                  ""stat_type"":""dex"",
                  ""name"":""wattire""
               },
               ""pants"":{
                  ""level"":9,
                  ""stat_type"":""int"",
                  ""name"":""wbreeches""
               },
               ""shoes"":{
                  ""name"":""wingedboots"",
                  ""level"":8
               },
               ""gloves"":null,
               ""amulet"":{
                  ""name"":""warmscarf"",
                  ""level"":9
               },
               ""orb"":null,
               ""elixir"":null,
               ""cape"":{
                  ""level"":0,
                  ""name"":""stealthcape""
               },
               ""trade1"":null,
               ""trade2"":null,
               ""trade3"":null,
               ""trade4"":null
            },
            ""ctype"":""merchant"",
            ""owner"":""4667600492560384""
         },
         {
            ""hp"":7826,
            ""max_hp"":7826,
            ""mp"":2020,
            ""max_mp"":2060,
            ""xp"":10375841,
            ""attack"":310,
            ""frequency"":0.670161149825784,
            ""speed"":75,
            ""range"":32,
            ""armor"":141,
            ""resistance"":221,
            ""level"":54,
            ""rip"":false,
            ""afk"":false,
            ""target"":""2156802"",
            ""focus"":null,
            ""s"":{
               ""mluck"":{
                  ""ms"":709000,
                  ""f"":""Dinger""
               }
            },
            ""c"":{
               
            },
            ""q"":{
               
            },
            ""age"":69,
            ""pdps"":0,
            ""id"":""sichi"",
            ""x"":0,
            ""y"":-37,
            ""moving"":false,
            ""going_x"":151.07654357633953,
            ""going_y"":-144.9999999,
            ""abs"":false,
            ""move_num"":17364945,
            ""angle"":-64.12607348356174,
            ""cid"":8,
            ""stand"":false,
            ""skin"":""sarmor2c"",
            ""cx"":{
               ""hat"":""hat322""
            },
            ""slots"":{
               ""ring1"":{
                  ""name"":""vitring"",
                  ""level"":3
               },
               ""ring2"":{
                  ""name"":""ringsj"",
                  ""level"":3
               },
               ""earring1"":{
                  ""level"":0,
                  ""name"":""vitearring""
               },
               ""earring2"":{
                  ""name"":""vitearring"",
                  ""level"":1
               },
               ""belt"":{
                  ""level"":0,
                  ""m"":""Chonk003"",
                  ""name"":""hpbelt""
               },
               ""mainhand"":{
                  ""name"":""carrotsword"",
                  ""level"":7
               },
               ""offhand"":null,
               ""helmet"":{
                  ""stat_type"":""vit"",
                  ""name"":""eears"",
                  ""level"":7
               },
               ""chest"":{
                  ""level"":7,
                  ""stat_type"":""vit"",
                  ""name"":""epyjamas""
               },
               ""pants"":{
                  ""level"":3,
                  ""stat_type"":""vit"",
                  ""name"":""wbreeches""
               },
               ""shoes"":{
                  ""level"":8,
                  ""stat_type"":""vit"",
                  ""name"":""eslippers""
               },
               ""gloves"":{
                  ""level"":7,
                  ""stat_type"":""vit"",
                  ""name"":""wgloves""
               },
               ""amulet"":{
                  ""level"":6,
                  ""name"":""warmscarf""
               },
               ""orb"":{
                  ""level"":0,
                  ""name"":""test_orb""
               },
               ""elixir"":null,
               ""cape"":{
                  ""level"":5,
                  ""stat_type"":""vit"",
                  ""name"":""angelwings""
               },
               ""trade1"":null,
               ""trade2"":null,
               ""trade3"":null,
               ""trade4"":{
                  ""name"":""staff"",
                  ""price"":40000000,
                  ""rid"":""TfCh"",
                  ""level"":9
               }
            },
            ""ctype"":""merchant"",
            ""owner"":""6000633860063232""
         }
      ],
      ""monsters"":[
         
      ],
      ""type"":""all"",
      ""in"":""bank"",
      ""map"":""bank""
   }
}";

            var obj = JsonConvert.DeserializeObject<NewMapData>(NEW_MAP_DATA);

            Assert.IsNotNull(obj);
        }

        [TestMethod]
        public void DeserializeNotThereDataTest()
        {
            const string NOT_THERE_DATA = @"{
   ""place"":""attack""
}";

            var obj = JsonConvert.DeserializeObject<NotThereData>(NOT_THERE_DATA);

            Assert.IsNotNull(obj);
        }

        [TestMethod]
        public void DeserializePartyUpdateDataTest()
        {
            const string PARTY_UPDATE_DATA = @"{
   ""list"":[
      ""earthMer"",
      ""myranger"",
      ""sichi""
   ],
   ""party"":{
      ""earthMer"":{
         ""skin"":""marmor12a"",
         ""level"":74,
         ""type"":""merchant"",
         ""x"":153.3969219854852,
         ""y"":-124.03322858515753,
         ""in"":""main"",
         ""map"":""main"",
         ""share"":0,
         ""pdps"":2.403978062438949e-15,
         ""l"":1,
         ""xp"":0,
         ""luck"":10,
         ""gold"":5,
         ""cx"":{
            ""hair"":""hairdo520"",
            ""head"":""fmakeup01""
         }
      },
      ""myranger"":{
         ""skin"":""marmor5a"",
         ""level"":44,
         ""type"":""ranger"",
         ""x"":-7.871881376000971,
         ""y"":57.14241936867256,
         ""in"":""main"",
         ""map"":""main"",
         ""share"":0.9999999899997225,
         ""pdps"":0,
         ""l"":1,
         ""xp"":0,
         ""luck"":10,
         ""gold"":5,
         ""cx"":{
            ""hair"":""hairdo106"",
            ""head"":""makeup117""
         }
      },
      ""sichi"":{
         ""skin"":""sarmor2c"",
         ""level"":54,
         ""type"":""merchant"",
         ""x"":-86.51955384018893,
         ""y"":-95.46821799675385,
         ""in"":""main"",
         ""map"":""main"",
         ""share"":0,
         ""pdps"":0,
         ""l"":1,
         ""xp"":0,
         ""luck"":10,
         ""gold"":5,
         ""cx"":{
            ""hat"":""hat322""
         }
      }
   },
   ""message"":""sichi joined the party""
}";

            var obj = JsonConvert.DeserializeObject<PartyUpdateData>(PARTY_UPDATE_DATA);

            Assert.IsNotNull(obj);
        }

        [TestMethod]
        public void DeserializePingAckDataTest()
        {
            const string PING_ACK_DATA = @"{
   ""id"":""aKHAz""
}";

            var obj = JsonConvert.DeserializeObject<PingAckData>(PING_ACK_DATA);

            Assert.IsNotNull(obj);
        }

        [TestMethod]
        public void DeserializeQueueActionDataTest()
        {
            const string QUEUED_ACTION_DATA = @"{
   ""q"":{
      ""upgrade"":{
         ""ms"":161,
         ""len"":500,
         ""num"":1
      }
   },
   ""num"":1,
   ""p"":{
      ""chance"":0.9999999,
      ""name"":""blade"",
      ""level"":0,
      ""scroll"":""scroll0"",
      ""nums"":[
         1,
         0
      ]
   }
}";

            var obj = JsonConvert.DeserializeObject<QueuedActionData>(QUEUED_ACTION_DATA);

            Assert.IsNotNull(obj);
        }

        [TestMethod]
        public void DeserializeQueuedActionResultDataTest()
        {
            const string QUEUED_ACTION_RESULT_DATA = @"{
   ""type"":""compound"",
   ""success"":1
}";

            var obj = JsonConvert.DeserializeObject<QueuedActionResultData>(QUEUED_ACTION_RESULT_DATA);

            Assert.IsNotNull(obj);
        }

        [TestMethod]
        public void DeserializeSecondHandsDataTest()
        {
           const string SECONDHANDS_DATA = @"[
   {
      ""q"":9999,
      ""rid"":""AbUEw"",
      ""name"":""vitscroll""
   },
   {
      ""q"":9999,
      ""rid"":""nTZVO"",
      ""name"":""vitscroll""
   },
   {
      ""q"":9999,
      ""rid"":""XG6Jb"",
      ""name"":""vitscroll""
   },
   {
      ""q"":9999,
      ""rid"":""WyHTq"",
      ""name"":""vitscroll""
   },
   {
      ""q"":9999,
      ""rid"":""QeSVe"",
      ""name"":""vitscroll""
   },
   {
      ""acc"":1,
      ""rid"":""vZCHK"",
      ""level"":3,
      ""name"":""spear""
   },
   {
      ""rid"":""HhP6B"",
      ""level"":4,
      ""name"":""spear""
   },
   {
      ""rid"":""OMN9v"",
      ""name"":""spear"",
      ""level"":0
   },
   {
      ""rid"":""oqdXN"",
      ""name"":""spear"",
      ""level"":0
   },
   {
      ""rid"":""TfufP"",
      ""name"":""spear"",
      ""level"":0
   },
   {
      ""rid"":""POvvK"",
      ""name"":""spear"",
      ""level"":0
   },
   {
      ""rid"":""ltmOX"",
      ""name"":""spear"",
      ""level"":0
   },
   {
      ""rid"":""O8iy7"",
      ""name"":""spear"",
      ""level"":3
   },
   {
      ""rid"":""CZRaL"",
      ""name"":""spear"",
      ""level"":3
   },
   {
      ""rid"":""eGpeI"",
      ""name"":""spear"",
      ""level"":3
   },
   {
      ""q"":100,
      ""rid"":""mnlk6"",
      ""name"":""smoke""
   },
   {
      ""rid"":""BSaKC"",
      ""name"":""iceskates"",
      ""level"":0
   },
   {
      ""rid"":""tfZTD"",
      ""name"":""gloves1"",
      ""level"":1
   },
   {
      ""rid"":""umTgl"",
      ""name"":""gloves1"",
      ""level"":1
   },
   {
      ""rid"":""trZ1v"",
      ""name"":""gloves1"",
      ""level"":1
   },
   {
      ""rid"":""U8ZXU"",
      ""name"":""coat1"",
      ""level"":0
   },
   {
      ""rid"":""y3BUL"",
      ""name"":""gphelmet"",
      ""level"":0
   },
   {
      ""rid"":""JRUBm"",
      ""name"":""gphelmet"",
      ""level"":0
   },
   {
      ""rid"":""koSiM"",
      ""name"":""gphelmet"",
      ""level"":0
   },
   {
      ""rid"":""AF8vK"",
      ""name"":""gphelmet"",
      ""level"":0
   },
   {
      ""rid"":""ngvFD"",
      ""name"":""gphelmet"",
      ""level"":0
   },
   {
      ""rid"":""zwbmX"",
      ""name"":""phelmet"",
      ""level"":0
   },
   {
      ""rid"":""izTeD"",
      ""name"":""phelmet"",
      ""level"":0
   },
   {
      ""rid"":""ooF6I"",
      ""name"":""phelmet"",
      ""level"":0
   },
   {
      ""rid"":""TIQtD"",
      ""name"":""phelmet"",
      ""level"":0
   },
   {
      ""rid"":""KmIKk"",
      ""name"":""phelmet"",
      ""level"":0
   },
   {
      ""rid"":""ln2Xz"",
      ""name"":""slimestaff"",
      ""level"":0
   },
   {
      ""rid"":""hs3bt"",
      ""name"":""slimestaff"",
      ""level"":0
   },
   {
      ""rid"":""iy4iy"",
      ""name"":""slimestaff"",
      ""level"":0
   },
   {
      ""rid"":""dcHNZ"",
      ""name"":""slimestaff"",
      ""level"":0
   },
   {
      ""rid"":""EnwZm"",
      ""name"":""slimestaff"",
      ""level"":0
   },
   {
      ""rid"":""TyFuv"",
      ""name"":""coat1"",
      ""level"":0
   },
   {
      ""rid"":""qXXqp"",
      ""name"":""shoes1"",
      ""level"":0
   },
   {
      ""rid"":""cSZDo"",
      ""name"":""shoes1"",
      ""level"":0
   },
   {
      ""rid"":""cc3T4"",
      ""name"":""hpamulet"",
      ""level"":0
   },
   {
      ""rid"":""I8H4R"",
      ""name"":""hpbelt"",
      ""level"":0
   },
   {
      ""rid"":""p228L"",
      ""name"":""hpamulet"",
      ""level"":0
   },
   {
      ""rid"":""ZOQcT"",
      ""name"":""hpbelt"",
      ""level"":0
   },
   {
      ""rid"":""TxUwW"",
      ""name"":""hpamulet"",
      ""level"":0
   },
   {
      ""rid"":""SA7gv"",
      ""name"":""hpamulet"",
      ""level"":0
   },
   {
      ""rid"":""Pmzko"",
      ""level"":2,
      ""name"":""hpbelt""
   },
   {
      ""rid"":""Lu6dU"",
      ""level"":1,
      ""name"":""hpbelt""
   },
   {
      ""rid"":""TksLH"",
      ""level"":1,
      ""name"":""hpbelt""
   },
   {
      ""rid"":""NPX1x"",
      ""name"":""hpbelt"",
      ""level"":0
   },
   {
      ""rid"":""Qr65x"",
      ""name"":""hpbelt"",
      ""level"":0
   },
   {
      ""q"":100,
      ""rid"":""kJVM6"",
      ""name"":""smoke""
   },
   {
      ""rid"":""amZtT"",
      ""level"":6,
      ""name"":""mushroomstaff""
   },
   {
      ""rid"":""KgdHb"",
      ""level"":2,
      ""name"":""hpbelt""
   },
   {
      ""acc"":1,
      ""rid"":""XEDFV"",
      ""name"":""blade"",
      ""level"":7
   },
   {
      ""rid"":""TJuv3"",
      ""level"":2,
      ""name"":""hpbelt""
   },
   {
      ""rid"":""RTRg8"",
      ""level"":2,
      ""name"":""hpamulet""
   },
   {
      ""rid"":""TSO0d"",
      ""name"":""iceskates"",
      ""level"":0
   },
   {
      ""rid"":""EdNLt"",
      ""level"":2,
      ""name"":""hpamulet""
   },
   {
      ""rid"":""NTJtl"",
      ""level"":2,
      ""name"":""hpbelt""
   },
   {
      ""rid"":""UbpRR"",
      ""level"":2,
      ""name"":""hpamulet""
   },
   {
      ""rid"":""BtoJE"",
      ""level"":2,
      ""name"":""hpamulet""
   },
   {
      ""rid"":""bdvGU"",
      ""name"":""pants1"",
      ""level"":0
   },
   {
      ""rid"":""EpKEV"",
      ""name"":""pants1"",
      ""level"":0
   },
   {
      ""rid"":""DckSS"",
      ""level"":1,
      ""name"":""hpamulet""
   },
   {
      ""rid"":""qHpUH"",
      ""level"":1,
      ""name"":""hpamulet""
   },
   {
      ""rid"":""bSyTO"",
      ""level"":1,
      ""name"":""hpamulet""
   },
   {
      ""rid"":""geU0E"",
      ""level"":1,
      ""name"":""hpamulet""
   },
   {
      ""rid"":""eqB5V"",
      ""level"":1,
      ""name"":""hpamulet""
   },
   {
      ""rid"":""MCS8K"",
      ""level"":2,
      ""name"":""hpamulet""
   },
   {
      ""rid"":""LSF19"",
      ""level"":1,
      ""name"":""hpbelt""
   },
   {
      ""rid"":""kfln2"",
      ""level"":1,
      ""name"":""hpbelt""
   },
   {
      ""q"":100,
      ""rid"":""ZmsRJ"",
      ""name"":""smoke""
   },
   {
      ""q"":100,
      ""rid"":""Fsslg"",
      ""name"":""smoke""
   },
   {
      ""q"":100,
      ""rid"":""KZoEt"",
      ""name"":""smoke""
   },
   {
      ""q"":110,
      ""rid"":""NbTWc"",
      ""name"":""snowball""
   },
   {
      ""rid"":""kan4i"",
      ""name"":""iceskates"",
      ""level"":0
   },
   {
      ""rid"":""QCH06"",
      ""name"":""iceskates"",
      ""level"":0
   },
   {
      ""rid"":""q2L9L"",
      ""name"":""iceskates"",
      ""level"":0
   },
   {
      ""rid"":""CwaNM"",
      ""name"":""warmscarf"",
      ""level"":0
   },
   {
      ""rid"":""evvAw"",
      ""name"":""warmscarf"",
      ""level"":0
   },
   {
      ""rid"":""tTbM7"",
      ""name"":""warmscarf"",
      ""level"":0
   },
   {
      ""rid"":""nSQXM"",
      ""name"":""hpamulet"",
      ""level"":0
   },
   {
      ""rid"":""T36WK"",
      ""name"":""gloves1"",
      ""level"":0
   },
   {
      ""rid"":""m8thN"",
      ""name"":""gloves1"",
      ""level"":0
   },
   {
      ""rid"":""gF4tD"",
      ""name"":""helmet1"",
      ""level"":0
   },
   {
      ""rid"":""uk2Q2"",
      ""name"":""coat1"",
      ""level"":0
   },
   {
      ""rid"":""JokEK"",
      ""name"":""coat1"",
      ""level"":0
   },
   {
      ""rid"":""ZtevX"",
      ""name"":""shoes1"",
      ""level"":0
   },
   {
      ""rid"":""xx4OI"",
      ""name"":""pants1"",
      ""level"":0
   },
   {
      ""rid"":""XlWb2"",
      ""name"":""coat1"",
      ""level"":0
   },
   {
      ""rid"":""f79JR"",
      ""name"":""pants1"",
      ""level"":0
   },
   {
      ""rid"":""hlhHJ"",
      ""name"":""shoes1"",
      ""level"":0
   },
   {
      ""rid"":""bLtxR"",
      ""name"":""shoes1"",
      ""level"":0
   },
   {
      ""rid"":""DaCW3"",
      ""name"":""helmet1"",
      ""level"":0
   },
   {
      ""rid"":""KkCJT"",
      ""name"":""helmet1"",
      ""level"":0
   },
   {
      ""rid"":""JcXAo"",
      ""name"":""pants1"",
      ""level"":0
   },
   {
      ""rid"":""euF3t"",
      ""name"":""gloves1"",
      ""level"":0
   },
   {
      ""rid"":""EFO24"",
      ""name"":""helmet1"",
      ""level"":0
   },
   {
      ""rid"":""GS0uD"",
      ""name"":""helmet1"",
      ""level"":0
   },
   {
      ""rid"":""w7cTk"",
      ""name"":""gloves1"",
      ""level"":0
   },
   {
      ""rid"":""uW9ga"",
      ""level"":1,
      ""name"":""hpbelt""
   },
   {
      ""rid"":""mbr3o"",
      ""name"":""gloves1"",
      ""level"":0
   },
   {
      ""rid"":""Pg120"",
      ""m"":""MageMain"",
      ""name"":""hpbelt"",
      ""level"":0
   },
   {
      ""q"":1,
      ""rid"":""kOp5f"",
      ""name"":""elixirvit0""
   },
   {
      ""rid"":""sdToZ"",
      ""name"":""dagger"",
      ""level"":6
   },
   {
      ""rid"":""vwKKn"",
      ""stat_type"":""int"",
      ""name"":""helmet1"",
      ""level"":4
   },
   {
      ""rid"":""SrzcQ"",
      ""stat_type"":""int"",
      ""name"":""shoes1"",
      ""level"":4
   },
   {
      ""rid"":""NLIpA"",
      ""stat_type"":""int"",
      ""name"":""helmet1"",
      ""level"":4
   },
   {
      ""rid"":""EHm2l"",
      ""name"":""dagger"",
      ""level"":0
   },
   {
      ""rid"":""GC5Dc"",
      ""name"":""dagger"",
      ""level"":0
   },
   {
      ""rid"":""gA0Id"",
      ""name"":""dagger"",
      ""level"":0
   },
   {
      ""rid"":""S6SqL"",
      ""name"":""xmassweater"",
      ""level"":0
   },
   {
      ""rid"":""Op6FA"",
      ""name"":""xmassweater"",
      ""level"":0
   },
   {
      ""rid"":""CLw6X"",
      ""name"":""xmassweater"",
      ""level"":0
   },
   {
      ""rid"":""veZEh"",
      ""name"":""xmassweater"",
      ""level"":0
   },
   {
      ""rid"":""r7UqI"",
      ""name"":""xmassweater"",
      ""level"":0
   },
   {
      ""rid"":""Gdzuh"",
      ""name"":""dagger"",
      ""level"":0
   },
   {
      ""rid"":""QKhBF"",
      ""name"":""dagger"",
      ""level"":0
   },
   {
      ""rid"":""o10eu"",
      ""name"":""fieldgen0""
   },
   {
      ""rid"":""nA77u"",
      ""name"":""fieldgen0""
   },
   {
      ""rid"":""vyiyg"",
      ""name"":""fieldgen0""
   },
   {
      ""rid"":""J4ylH"",
      ""name"":""fieldgen0""
   },
   {
      ""rid"":""pqieN"",
      ""name"":""fieldgen0""
   },
   {
      ""rid"":""L8rTC"",
      ""name"":""ringsj"",
      ""level"":0
   },
   {
      ""rid"":""XkSR2"",
      ""name"":""ringsj"",
      ""level"":0
   },
   {
      ""rid"":""vAOsO"",
      ""name"":""ringsj"",
      ""level"":0
   },
   {
      ""rid"":""n6U1R"",
      ""name"":""ringsj"",
      ""level"":0
   },
   {
      ""rid"":""wqtSq"",
      ""name"":""ringsj"",
      ""level"":0
   },
   {
      ""name"":""quiver"",
      ""level"":2,
      ""rid"":""BZ7yu""
   },
   {
      ""name"":""quiver"",
      ""level"":3,
      ""rid"":""dF7Ac""
   },
   {
      ""name"":""quiver"",
      ""level"":3,
      ""rid"":""UA1Jq""
   },
   {
      ""name"":""quiver"",
      ""level"":3,
      ""rid"":""xWA2T""
   },
   {
      ""name"":""quiver"",
      ""level"":3,
      ""rid"":""e5A02""
   },
   {
      ""name"":""quiver"",
      ""level"":2,
      ""rid"":""vQrJf""
   },
   {
      ""name"":""quiver"",
      ""level"":2,
      ""rid"":""l4yq2""
   },
   {
      ""name"":""quiver"",
      ""level"":2,
      ""rid"":""kGiJR""
   },
   {
      ""name"":""quiver"",
      ""level"":2,
      ""rid"":""VHD9E""
   },
   {
      ""name"":""quiver"",
      ""level"":3,
      ""rid"":""PTAz4""
   },
   {
      ""name"":""cclaw"",
      ""level"":0,
      ""rid"":""fUicB""
   },
   {
      ""name"":""stinger"",
      ""level"":0,
      ""rid"":""diVWD""
   },
   {
      ""name"":""cclaw"",
      ""level"":0,
      ""rid"":""XzW5i""
   },
   {
      ""name"":""cclaw"",
      ""level"":0,
      ""rid"":""FAhKo""
   },
   {
      ""name"":""cclaw"",
      ""level"":0,
      ""rid"":""Ceqnx""
   },
   {
      ""name"":""cclaw"",
      ""level"":0,
      ""rid"":""uGzyP""
   },
   {
      ""q"":3,
      ""name"":""ijx"",
      ""rid"":""kJsPd""
   },
   {
      ""name"":""stinger"",
      ""level"":0,
      ""rid"":""TeEAP""
   },
   {
      ""name"":""crabclaw"",
      ""q"":4,
      ""rid"":""bx3NL""
   },
   {
      ""name"":""stinger"",
      ""level"":0,
      ""m"":""Terazarrior"",
      ""rid"":""unIIJ""
   },
   {
      ""name"":""stinger"",
      ""level"":0,
      ""rid"":""W5JLz""
   },
   {
      ""name"":""spores"",
      ""q"":23,
      ""rid"":""TJJyv""
   },
   {
      ""name"":""stinger"",
      ""level"":0,
      ""rid"":""pXHt2""
   },
   {
      ""name"":""mushroomstaff"",
      ""level"":0,
      ""rid"":""Bl7UX""
   },
   {
      ""name"":""throwingstars"",
      ""level"":0,
      ""rid"":""DA1Al""
   },
   {
      ""name"":""vitearring"",
      ""level"":0,
      ""m"":""Dooba"",
      ""rid"":""lUz2c""
   }
]";

            var obj = JsonConvert.DeserializeObject<TradeItem[]>(SECONDHANDS_DATA);

            Assert.IsNotNull(obj);
            Assert.IsTrue(obj.Any());
        }

        [TestMethod]
        public void DeserializeStartDataTest()
        {
            const string START_DATA = @"{
   ""hp"":7826,
   ""max_hp"":7826,
   ""mp"":2020,
   ""max_mp"":2060,
   ""xp"":10375841,
   ""attack"":310,
   ""frequency"":0.670161149825784,
   ""speed"":75,
   ""range"":32,
   ""armor"":141,
   ""resistance"":221,
   ""level"":54,
   ""rip"":false,
   ""afk"":true,
   ""s"":{
      ""mluck"":{
         ""ms"":1484664,
         ""f"":""Dinger""
      }
   },
   ""c"":{
      
   },
   ""q"":{
      
   },
   ""age"":69,
   ""pdps"":0,
   ""id"":""sichi"",
   ""x"":40.40316655490353,
   ""y"":541.1426134776386,
   ""cid"":1,
   ""stand"":false,
   ""skin"":""sarmor2c"",
   ""cx"":{
      ""hat"":""hat322""
   },
   ""slots"":{
      ""ring1"":{
         ""name"":""vitring"",
         ""level"":3
      },
      ""ring2"":{
         ""name"":""ringsj"",
         ""level"":3
      },
      ""earring1"":{
         ""level"":0,
         ""name"":""vitearring""
      },
      ""earring2"":{
         ""name"":""vitearring"",
         ""level"":1
      },
      ""belt"":{
         ""level"":0,
         ""m"":""Chonk003"",
         ""name"":""hpbelt""
      },
      ""mainhand"":{
         ""name"":""carrotsword"",
         ""level"":7
      },
      ""offhand"":null,
      ""helmet"":{
         ""stat_type"":""vit"",
         ""name"":""eears"",
         ""level"":7
      },
      ""chest"":{
         ""level"":7,
         ""stat_type"":""vit"",
         ""name"":""epyjamas""
      },
      ""pants"":{
         ""level"":3,
         ""stat_type"":""vit"",
         ""name"":""wbreeches""
      },
      ""shoes"":{
         ""level"":8,
         ""stat_type"":""vit"",
         ""name"":""eslippers""
      },
      ""gloves"":{
         ""level"":7,
         ""stat_type"":""vit"",
         ""name"":""wgloves""
      },
      ""amulet"":{
         ""level"":6,
         ""name"":""warmscarf""
      },
      ""orb"":{
         ""level"":0,
         ""name"":""test_orb""
      },
      ""elixir"":null,
      ""cape"":{
         ""level"":5,
         ""stat_type"":""vit"",
         ""name"":""angelwings""
      },
      ""trade1"":null,
      ""trade2"":null,
      ""trade3"":null,
      ""trade4"":{
         ""name"":""staff"",
         ""price"":40000000,
         ""rid"":""TfCh"",
         ""level"":9
      }
   },
   ""ctype"":""merchant"",
   ""owner"":""1234"",
   ""int"":90,
   ""str"":19,
   ""dex"":52,
   ""vit"":89,
   ""for"":3,
   ""mp_cost"":65,
   ""mp_reduction"":20,
   ""max_xp"":13000000,
   ""goldm"":1.01,
   ""xpm"":1.01,
   ""luckm"":1.17,
   ""map"":""main"",
   ""in"":""main"",
   ""isize"":42,
   ""esize"":26,
   ""gold"":37500000,
   ""cash"":427,
   ""targets"":0,
   ""m"":0,
   ""evasion"":4.45,
   ""miss"":0,
   ""reflection"":0,
   ""lifesteal"":0,
   ""manasteal"":0,
   ""rpiercing"":13,
   ""apiercing"":13,
   ""crit"":0,
   ""critdamage"":0,
   ""dreturn"":0,
   ""tax"":0.03,
   ""xrange"":25,
   ""pnresistance"":0,
   ""firesistance"":20,
   ""fzresistance"":20,
   ""stun"":0,
   ""blast"":0,
   ""explosion"":0,
   ""courage"":1,
   ""mcourage"":0,
   ""pcourage"":0,
   ""fear"":0,
   ""items"":[
      {
         ""name"":""stand0""
      },
      {
         ""name"":""blade"",
         ""level"":0
      },
      {
         ""q"":42,
         ""name"":""gemfragment""
      },
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      {
         ""q"":50,
         ""name"":""cscroll0""
      },
      {
         ""q"":26,
         ""name"":""cscroll1""
      },
      null,
      null,
      null,
      null,
      null,
      {
         ""q"":50,
         ""name"":""scroll0""
      },
      {
         ""q"":25,
         ""name"":""scroll1""
      },
      {
         ""q"":16,
         ""name"":""scroll2""
      },
      {
         ""name"":""tracker""
      },
      null,
      null,
      null,
      {
         ""q"":151,
         ""name"":""intscroll""
      },
      {
         ""q"":50,
         ""name"":""dexscroll""
      },
      {
         ""q"":62,
         ""name"":""strscroll""
      },
      {
         ""q"":9000,
         ""name"":""mpot0""
      },
      {
         ""q"":9000,
         ""name"":""hpot0""
      },
      {
         ""q"":9000,
         ""name"":""hpot1""
      },
      {
         ""q"":9000,
         ""name"":""mpot1""
      }
   ],
   ""cc"":4,
   ""ipass"":""RW9UQZ6TiKXh"",
   ""friends"":[
      ""6341309189586944""
   ],
   ""acx"":{
      ""hat219"":1,
      ""mbody2d"":1,
      ""sbody1e"":1,
      ""pinkb"":1,
      ""hairdo222"":1,
      ""marmor8c"":1,
      ""marmor6h"":1,
      ""marmor11d"":1,
      ""sarmor2c"":1,
      ""marmor8d"":1,
      ""hat200"":2,
      ""hat202"":1,
      ""hairdo415"":1,
      ""marmor3d"":1,
      ""hairdo516"":1,
      ""hat322"":1,
      ""hat305"":1,
      ""hat108"":1,
      ""hairdo105"":1,
      ""mbody4h"":1,
      ""marmor7e"":1,
      ""sarmor1c"":1,
      ""marmor10b"":1,
      ""marmor10c"":1,
      ""marmor10a"":1,
      ""hat211"":2,
      ""hat312"":1,
      ""hairdo406"":1,
      ""hat311"":1,
      ""marmor2g"":2
   },
   ""xcx"":[
      
   ],
   ""emx"":{
      
   },
   ""info"":{
      
   },
   ""base_gold"":{
      ""stompy"":{
         ""winterland"":36724
      },
      ""wolf"":{
         ""winterland"":2960
      },
      ""arcticbee"":{
         ""winterland"":78
      },
      ""wolfie"":{
         ""winterland"":1235
      },
      ""boar"":{
         ""winterland"":587
      },
      ""iceroamer"":{
         ""winterland"":196
      },
      ""icegolem"":{
         ""winterland"":7731924
      },
      ""rat"":{
         ""mansion"":50
      },
      ""d_wiz"":{
         ""d2"":16528
      },
      ""bat"":{
         ""batcave"":106,
         ""old_main"":106,
         ""cave"":68
      },
      ""mvampire"":{
         ""batcave"":6740,
         ""cave"":6740
      },
      ""xmagefz"":{
         ""winter_instance"":449998
      },
      ""xmagefi"":{
         ""winter_instance"":702110
      },
      ""xmagen"":{
         ""winter_instance"":513598
      },
      ""xmagex"":{
         ""winter_instance"":52930167
      },
      ""crab"":{
         ""main"":17
      },
      ""squig"":{
         ""main"":61
      },
      ""squigtoad"":{
         ""main"":41
      },
      ""tortoise"":{
         ""main"":97
      },
      ""frog"":{
         ""main"":41
      },
      ""crabx"":{
         ""main"":118
      },
      ""target"":{
         ""main"":20
      },
      ""target_a500"":{
         ""main"":20
      },
      ""target_a750"":{
         ""main"":20
      },
      ""target_r500"":{
         ""main"":20
      },
      ""target_r750"":{
         ""main"":20
      },
      ""target_ar900"":{
         ""main"":20
      },
      ""target_ar500red"":{
         ""main"":20
      },
      ""goo"":{
         ""main"":9,
         ""dungeon0"":16,
         ""old_main"":9,
         ""goobrawl"":9
      },
      ""bee"":{
         ""main"":26
      },
      ""poisio"":{
         ""main"":58
      },
      ""croc"":{
         ""main"":61
      },
      ""armadillo"":{
         ""main"":55
      },
      ""snake"":{
         ""main"":44,
         ""halloween"":44
      },
      ""bigbird"":{
         ""main"":899
      },
      ""spider"":{
         ""main"":87,
         ""old_main"":121
      },
      ""scorpion"":{
         ""main"":68,
         ""old_main"":140,
         ""desertland"":140
      },
      ""phoenix"":{
         ""main"":4493,
         ""old_main"":4493
      },
      ""greenfairy"":{
         ""main"":101088
      },
      ""redfairy"":{
         ""main"":134784
      },
      ""bluefairy"":{
         ""main"":112320
      },
      ""puppy1"":{
         ""main"":20,
         ""shellsisland"":20
      },
      ""puppy2"":{
         ""main"":20,
         ""shellsisland"":20
      },
      ""puppy3"":{
         ""main"":20,
         ""shellsisland"":20
      },
      ""puppy4"":{
         ""main"":20,
         ""shellsisland"":20
      },
      ""kitty1"":{
         ""main"":20,
         ""shellsisland"":20
      },
      ""kitty2"":{
         ""main"":20,
         ""shellsisland"":20
      },
      ""kitty3"":{
         ""main"":20,
         ""shellsisland"":20
      },
      ""kitty4"":{
         ""main"":20,
         ""shellsisland"":20
      },
      ""hen"":{
         ""main"":6
      },
      ""rooster"":{
         ""main"":6
      },
      ""mole"":{
         ""tunnel"":798
      },
      ""pinkgoblin"":{
         ""level2e"":79530
      },
      ""osnake"":{
         ""halloween"":44
      },
      ""greenjr"":{
         ""halloween"":236
      },
      ""minimush"":{
         ""halloween"":34
      },
      ""xscorpion"":{
         ""halloween"":905
      },
      ""tinyp"":{
         ""halloween"":158
      },
      ""ghost"":{
         ""halloween"":588
      },
      ""fvampire"":{
         ""halloween"":6740
      },
      ""prat"":{
         ""level1"":734
      },
      ""mummy"":{
         ""level3"":2002,
         ""level4"":2002,
         ""spookytown"":1126
      },
      ""bbpompom"":{
         ""level3"":397,
         ""winter_cave"":320
      },
      ""cgoo"":{
         ""level4"":348,
         ""level2s"":348,
         ""arena"":348
      },
      ""mechagnome"":{
         ""cyberland"":25509
      },
      ""dknight2"":{
         ""old_main"":6283
      },
      ""a1"":{
         ""crypt"":9537313
      },
      ""a7"":{
         ""crypt"":161741
      },
      ""a3"":{
         ""crypt"":76827
      },
      ""a6"":{
         ""crypt"":71885
      },
      ""a5"":{
         ""crypt"":51668
      },
      ""a2"":{
         ""crypt"":94349
      },
      ""a4"":{
         ""crypt"":210093
      },
      ""a8"":{
         ""crypt"":125799
      },
      ""vbat"":{
         ""crypt"":74469
      },
      ""booboo"":{
         ""spookytown"":281
      },
      ""stoneworm"":{
         ""spookytown"":65
      },
      ""jr"":{
         ""spookytown"":180
      },
      ""oneeye"":{
         ""level2w"":35997
      },
      ""pppompom"":{
         ""level2n"":4586
      },
      ""skeletor"":{
         ""arena"":2247
      },
      ""plantoid"":{
         ""desertland"":9874
      },
      ""porcupine"":{
         ""desertland"":86
      },
      ""ent"":{
         ""desertland"":675949
      },
      ""fireroamer"":{
         ""desertland"":6535
      },
      ""bscorpion"":{
         ""desertland"":36382
      },
      ""jrat"":{
         ""jail"":320
      },
      ""gredpro"":{
         ""tomb"":190619
      },
      ""ggreenpro"":{
         ""tomb"":44928
      },
      ""gbluepro"":{
         ""tomb"":311626
      },
      ""gpurplepro"":{
         ""tomb"":376650
      },
      ""grinch"":{
         ""woffice"":1098531
      }
   },
   ""s_info"":{
      ""icegolem"":{
         ""live"":true,
         ""map"":""winterland"",
         ""hp"":16000000,
         ""max_hp"":16000000,
         ""x"":808.9124940370274,
         ""y"":407.6040564394661
      },
      ""snowman"":{
         ""live"":true,
         ""map"":""winterland"",
         ""hp"":1200,
         ""max_hp"":1200,
         ""x"":1111.7317564125299,
         ""y"":-785.8382420118533
      },
      ""franky"":{
         ""live"":true,
         ""map"":""level2w"",
         ""hp"":120000000,
         ""max_hp"":120000000,
         ""x"":-310.2996589373313,
         ""y"":222.54235316675556
      },
      ""holidayseason"":true
   },
   ""code"":""load_code('library');\nlet _scripted_self = new _merchant(parent.character);\n\nfor(let info of _CONSTANTS.PARTY_INFO)\n   start_character(info.name, info.code_slot);\n\n//_scripted_self.visit_party = false;\n_scripted_self.execute();\n_scripted_self.visit_party = false;"",
   ""code_slot"":6648264596652032,
   ""code_version"":35,
   ""entities"":{
      ""players"":[
         {
            ""hp"":5000,
            ""max_hp"":5000,
            ""xp"":0,
            ""speed"":40,
            ""armor"":500,
            ""level"":100,
            ""npc"":""pvp"",
            ""allow"":true,
            ""s"":{
               
            },
            ""c"":{
               
            },
            ""q"":{
               
            },
            ""id"":""Ace"",
            ""x"":325,
            ""y"":499,
            ""moving"":false,
            ""going_x"":325,
            ""going_y"":499,
            ""abs"":false,
            ""move_num"":1012,
            ""angle"":50.042451069170916,
            ""cid"":0,
            ""skin"":""thehelmet"",
            ""cx"":{
               
            },
            ""ctype"":""pvp"",
            ""owner"":""""
         },
         {
            ""hp"":7826,
            ""max_hp"":7826,
            ""mp"":2020,
            ""max_mp"":2060,
            ""xp"":10375841,
            ""attack"":310,
            ""frequency"":0.670161149825784,
            ""speed"":75,
            ""range"":32,
            ""armor"":141,
            ""resistance"":221,
            ""level"":54,
            ""rip"":false,
            ""afk"":true,
            ""s"":{
               ""mluck"":{
                  ""ms"":1484664,
                  ""f"":""Dinger""
               }
            },
            ""c"":{
               
            },
            ""q"":{
               
            },
            ""age"":69,
            ""pdps"":0,
            ""id"":""sichi"",
            ""x"":40.40316655490353,
            ""y"":541.1426134776386,
            ""cid"":1,
            ""stand"":false,
            ""skin"":""sarmor2c"",
            ""cx"":{
               ""hat"":""hat322""
            },
            ""slots"":{
               ""ring1"":{
                  ""name"":""vitring"",
                  ""level"":3
               },
               ""ring2"":{
                  ""name"":""ringsj"",
                  ""level"":3
               },
               ""earring1"":{
                  ""level"":0,
                  ""name"":""vitearring""
               },
               ""earring2"":{
                  ""name"":""vitearring"",
                  ""level"":1
               },
               ""belt"":{
                  ""level"":0,
                  ""m"":""Chonk003"",
                  ""name"":""hpbelt""
               },
               ""mainhand"":{
                  ""name"":""carrotsword"",
                  ""level"":7
               },
               ""offhand"":null,
               ""helmet"":{
                  ""stat_type"":""vit"",
                  ""name"":""eears"",
                  ""level"":7
               },
               ""chest"":{
                  ""level"":7,
                  ""stat_type"":""vit"",
                  ""name"":""epyjamas""
               },
               ""pants"":{
                  ""level"":3,
                  ""stat_type"":""vit"",
                  ""name"":""wbreeches""
               },
               ""shoes"":{
                  ""level"":8,
                  ""stat_type"":""vit"",
                  ""name"":""eslippers""
               },
               ""gloves"":{
                  ""level"":7,
                  ""stat_type"":""vit"",
                  ""name"":""wgloves""
               },
               ""amulet"":{
                  ""level"":6,
                  ""name"":""warmscarf""
               },
               ""orb"":{
                  ""level"":0,
                  ""name"":""test_orb""
               },
               ""elixir"":null,
               ""cape"":{
                  ""level"":5,
                  ""stat_type"":""vit"",
                  ""name"":""angelwings""
               },
               ""trade1"":null,
               ""trade2"":null,
               ""trade3"":null,
               ""trade4"":{
                  ""name"":""staff"",
                  ""price"":40000000,
                  ""rid"":""TfCh"",
                  ""level"":9
               }
            },
            ""ctype"":""merchant"",
            ""owner"":""1234""
         }
      ],
      ""monsters"":[
         {
            ""hp"":49831,
            ""mp"":250,
            ""armor"":0,
            ""resistance"":0,
            ""id"":""30"",
            ""x"":-571,
            ""y"":323,
            ""going_x"":-571,
            ""going_y"":323,
            ""type"":""target"",
            ""cid"":1,
            ""s"":{
               
            }
         },
         {
            ""hp"":49076,
            ""mp"":250,
            ""resistance"":0,
            ""id"":""31"",
            ""x"":-290,
            ""y"":280,
            ""going_x"":-290,
            ""going_y"":280,
            ""type"":""target_a500"",
            ""cid"":1,
            ""s"":{
               
            }
         },
         {
            ""hp"":49942,
            ""mp"":250,
            ""resistance"":0,
            ""id"":""32"",
            ""x"":-270,
            ""y"":280,
            ""going_x"":-270,
            ""going_y"":280,
            ""type"":""target_a750"",
            ""cid"":1,
            ""s"":{
               
            }
         },
         {
            ""hp"":49834,
            ""mp"":250,
            ""armor"":0,
            ""id"":""33"",
            ""x"":-250,
            ""y"":280,
            ""going_x"":-250,
            ""going_y"":280,
            ""type"":""target_r500"",
            ""cid"":1,
            ""s"":{
               
            }
         },
         {
            ""hp"":48265,
            ""mp"":250,
            ""armor"":0,
            ""id"":""34"",
            ""x"":-230,
            ""y"":280,
            ""going_x"":-230,
            ""going_y"":280,
            ""type"":""target_r750"",
            ""cid"":1,
            ""s"":{
               
            }
         },
         {
            ""mp"":2500,
            ""id"":""36"",
            ""x"":-150,
            ""y"":400,
            ""going_x"":-150,
            ""going_y"":400,
            ""type"":""target_ar500red"",
            ""cid"":5019,
            ""s"":{
               ""self_healing"":{
                  ""ms"":523,
                  ""ability"":true
               }
            }
         },
         {
            ""hp"":49795,
            ""mp"":250,
            ""id"":""1085300"",
            ""x"":-210,
            ""y"":280,
            ""going_x"":-210,
            ""going_y"":280,
            ""type"":""target_ar900"",
            ""cid"":1,
            ""s"":{
               
            }
         },
         {
            ""speed"":13.92,
            ""hp"":2850,
            ""mp"":2,
            ""attack"":25,
            ""xp"":7200,
            ""frequency"":0.596,
            ""armor"":0,
            ""resistance"":0,
            ""max_hp"":2850,
            ""id"":""1217269"",
            ""x"":548.4499154949419,
            ""y"":798.5877992580928,
            ""moving"":true,
            ""going_x"":466.98475039497237,
            ""going_y"":733.8092086308545,
            ""abs"":false,
            ""move_num"":17328249,
            ""angle"":-141.50936070652222,
            ""type"":""bee"",
            ""cid"":262,
            ""s"":{
               
            },
            ""level"":18
         },
         {
            ""speed"":13.92,
            ""hp"":2850,
            ""mp"":2,
            ""attack"":25,
            ""xp"":7200,
            ""frequency"":0.596,
            ""armor"":0,
            ""resistance"":0,
            ""max_hp"":2850,
            ""id"":""1217313"",
            ""x"":520.6252736212838,
            ""y"":722.7979709189814,
            ""moving"":true,
            ""going_x"":449.26567130502895,
            ""going_y"":764.3447389257076,
            ""abs"":false,
            ""move_num"":17328156,
            ""angle"":149.79131170393975,
            ""type"":""bee"",
            ""cid"":262,
            ""s"":{
               
            },
            ""level"":18
         },
         {
            ""speed"":13.92,
            ""hp"":2850,
            ""mp"":2,
            ""attack"":25,
            ""xp"":7200,
            ""frequency"":0.596,
            ""armor"":0,
            ""resistance"":0,
            ""max_hp"":2850,
            ""id"":""1347564"",
            ""x"":510.3996501729594,
            ""y"":715.5447328201744,
            ""moving"":true,
            ""going_x"":497.86920594146557,
            ""going_y"":708.5262454280972,
            ""abs"":false,
            ""move_num"":17328181,
            ""angle"":-150.74616619065918,
            ""type"":""bee"",
            ""cid"":230,
            ""s"":{
               
            },
            ""level"":18
         },
         {
            ""speed"":13.92,
            ""hp"":1948,
            ""mp"":2,
            ""attack"":25,
            ""xp"":4800,
            ""frequency"":0.596,
            ""armor"":0,
            ""resistance"":0,
            ""max_hp"":1950,
            ""id"":""2144145"",
            ""x"":516.6640616697276,
            ""y"":1001.2202175114968,
            ""moving"":true,
            ""going_x"":446.52579675948107,
            ""going_y"":1024.4436394648008,
            ""abs"":false,
            ""move_num"":17328265,
            ""angle"":161.67981979206658,
            ""type"":""bee"",
            ""cid"":16,
            ""target"":null,
            ""s"":{
               
            },
            ""level"":12
         },
         {
            ""speed"":13.92,
            ""hp"":1945,
            ""mp"":2,
            ""attack"":25,
            ""xp"":4800,
            ""frequency"":0.596,
            ""armor"":0,
            ""resistance"":0,
            ""max_hp"":1950,
            ""id"":""2144167"",
            ""x"":552.6879349320658,
            ""y"":1031.6423056196854,
            ""moving"":true,
            ""going_x"":547.6287044311638,
            ""going_y"":1022.014043998557,
            ""abs"":false,
            ""move_num"":17328053,
            ""angle"":-117.71996300702611,
            ""type"":""bee"",
            ""cid"":19,
            ""target"":null,
            ""s"":{
               
            },
            ""level"":12
         },
         {
            ""speed"":7.76,
            ""hp"":600,
            ""mp"":1,
            ""attack"":7,
            ""xp"":1100,
            ""frequency"":0.488,
            ""armor"":0,
            ""resistance"":0,
            ""max_hp"":600,
            ""id"":""2156646"",
            ""x"":38.14691789177397,
            ""y"":837.7094933461999,
            ""moving"":true,
            ""going_x"":-142.10513290596236,
            ""going_y"":811.9843714727751,
            ""abs"":false,
            ""move_num"":17328138,
            ""angle"":-171.8777387845508,
            ""type"":""goo"",
            ""cid"":11,
            ""s"":{
               
            },
            ""level"":11
         },
         {
            ""speed"":7.76,
            ""hp"":600,
            ""mp"":1,
            ""attack"":7,
            ""xp"":1100,
            ""frequency"":0.488,
            ""armor"":0,
            ""resistance"":0,
            ""max_hp"":600,
            ""id"":""2156674"",
            ""x"":189.33460099818114,
            ""y"":807.1861043026652,
            ""moving"":true,
            ""going_x"":104.12668254289139,
            ""going_y"":725.737119678836,
            ""abs"":false,
            ""move_num"":17328149,
            ""angle"":-136.2920828940173,
            ""type"":""goo"",
            ""cid"":11,
            ""s"":{
               
            },
            ""level"":11
         },
         {
            ""speed"":7.76,
            ""hp"":502,
            ""mp"":1,
            ""attack"":7,
            ""xp"":1100,
            ""frequency"":0.488,
            ""armor"":0,
            ""resistance"":0,
            ""max_hp"":600,
            ""id"":""2156681"",
            ""x"":-109.4188226642083,
            ""y"":812.3790683401586,
            ""moving"":true,
            ""going_x"":179.01623628273512,
            ""going_y"":778.4831423080209,
            ""abs"":false,
            ""move_num"":17328192,
            ""angle"":-6.702467641712148,
            ""type"":""goo"",
            ""cid"":14,
            ""target"":null,
            ""s"":{
               
            },
            ""level"":11
         },
         {
            ""speed"":7.76,
            ""hp"":600,
            ""mp"":1,
            ""attack"":7,
            ""xp"":1100,
            ""frequency"":0.488,
            ""armor"":0,
            ""resistance"":0,
            ""max_hp"":600,
            ""id"":""2156737"",
            ""x"":-66.23426266104033,
            ""y"":797.8892522496952,
            ""moving"":true,
            ""going_x"":-6.465745648674499,
            ""going_y"":819.0123311139473,
            ""abs"":false,
            ""move_num"":17328033,
            ""angle"":19.46416228828492,
            ""type"":""goo"",
            ""cid"":11,
            ""s"":{
               
            },
            ""level"":11
         },
         {
            ""speed"":7.76,
            ""hp"":600,
            ""mp"":1,
            ""attack"":7,
            ""xp"":1100,
            ""frequency"":0.488,
            ""armor"":0,
            ""resistance"":0,
            ""max_hp"":600,
            ""id"":""2156802"",
            ""x"":81.86847406018357,
            ""y"":797.1819679127765,
            ""moving"":true,
            ""going_x"":206.42580424298797,
            ""going_y"":799.5868845751852,
            ""abs"":false,
            ""move_num"":17327698,
            ""angle"":1.1061127926553918,
            ""type"":""goo"",
            ""cid"":11,
            ""s"":{
               
            },
            ""level"":11
         },
         {
            ""speed"":7.76,
            ""hp"":600,
            ""mp"":1,
            ""attack"":7,
            ""xp"":1100,
            ""frequency"":0.488,
            ""armor"":0,
            ""resistance"":0,
            ""max_hp"":600,
            ""id"":""2156832"",
            ""x"":11.875073768829152,
            ""y"":821.8430472590748,
            ""moving"":true,
            ""going_x"":2.1917997550918926,
            ""going_y"":790.3156683278921,
            ""abs"":false,
            ""move_num"":17328062,
            ""angle"":-107.07374145801641,
            ""type"":""goo"",
            ""cid"":11,
            ""s"":{
               
            },
            ""level"":11
         },
         {
            ""speed"":7.76,
            ""hp"":600,
            ""mp"":1,
            ""attack"":7,
            ""xp"":1100,
            ""frequency"":0.488,
            ""armor"":0,
            ""resistance"":0,
            ""max_hp"":600,
            ""id"":""2156867"",
            ""x"":-44.66166110745081,
            ""y"":783.4483758503544,
            ""moving"":true,
            ""going_x"":-115.3171990214201,
            ""going_y"":727.7141994740928,
            ""abs"":false,
            ""move_num"":17327666,
            ""angle"":-141.733079419923,
            ""type"":""goo"",
            ""cid"":11,
            ""s"":{
               
            },
            ""level"":11
         },
         {
            ""speed"":7.76,
            ""hp"":600,
            ""mp"":1,
            ""attack"":7,
            ""xp"":1100,
            ""frequency"":0.488,
            ""armor"":0,
            ""resistance"":0,
            ""max_hp"":600,
            ""id"":""2157024"",
            ""x"":25.617321211611934,
            ""y"":774.625375842805,
            ""moving"":true,
            ""going_x"":-130.06356778644843,
            ""going_y"":825.9005049117468,
            ""abs"":false,
            ""move_num"":17327154,
            ""angle"":161.77016079936698,
            ""type"":""goo"",
            ""cid"":11,
            ""s"":{
               
            },
            ""level"":11
         },
         {
            ""speed"":7.76,
            ""hp"":600,
            ""mp"":1,
            ""attack"":7,
            ""xp"":1100,
            ""frequency"":0.488,
            ""armor"":0,
            ""resistance"":0,
            ""max_hp"":600,
            ""id"":""2157038"",
            ""x"":168.5034298523371,
            ""y"":770.3849359630829,
            ""moving"":true,
            ""going_x"":17.13261418577366,
            ""going_y"":780.0815802326213,
            ""abs"":false,
            ""move_num"":17328139,
            ""angle"":176.334704867194,
            ""type"":""goo"",
            ""cid"":11,
            ""s"":{
               
            },
            ""level"":11
         }
      ],
      ""type"":""all"",
      ""in"":""main"",
      ""map"":""main""
   }
}";

            var obj = JsonConvert.DeserializeObject<StartData>(START_DATA);

            Assert.IsNotNull(obj);
        }

        [TestMethod]
        public void DeserializeUIDataTest()
        {
            const string UI_DATA = @"{
   ""type"":""+$"",
   ""id"":""scrolls"",
   ""name"":""earthMag2"",
   ""item"":{
      ""name"":""mpot1"",
      ""q"":1
   }
}";

            var obj = JsonConvert.DeserializeObject<UIData>(UI_DATA);

            Assert.IsNotNull(obj);
        }

        [TestMethod]
        public void DeserializeWelcomeDataTest()
        {
            const string WELCOME_DATA = @"{
   ""region"":""US"",
   ""name"":""III"",
   ""pvp"":false,
   ""gameplay"":""normal"",
   ""info"":{
      
   },
   ""x"":-274,
   ""y"":-1177,
   ""map"":""desertland"",
   ""in"":""desertland""
}";

            var obj = JsonConvert.DeserializeObject<WelcomeData>(WELCOME_DATA);

            Assert.IsNotNull(obj);
        }
    }
}