using AL.Core.Json.Converters;
using Newtonsoft.Json;

namespace AL.Data.Items
{
    [JsonObject(ItemConverterType = typeof(AttributedObjectConverter<Item>))]
    public class ItemsDatum : DatumBase<Item>
    {
        public Item _5bucks { get; set; }
        public Item Ale { get; set; }
        public Item Amuletofm { get; set; }
        public Item Angelwings { get; set; }
        public Item Apiercingscroll { get; set; }
        public Item Apologybox { get; set; }
        public Item Armorbox { get; set; }
        public Item Armorring { get; set; }
        public Item Armorscroll { get; set; }
        public Item Ascale { get; set; }
        public Item Axe3 { get; set; }
        public Item Bandages { get; set; }
        public Item Basher { get; set; }
        public Item Basketofeggs { get; set; }
        public Item Bataxe { get; set; }
        public Item Bcandle { get; set; }
        public Item Bcape { get; set; }
        public Item Beewings { get; set; }
        public Item Bfang { get; set; }
        public Item Bfur { get; set; }
        public Item Bkey { get; set; }
        public Item Blade { get; set; }
        public Item Blue { get; set; }
        public Item Bottleofxp { get; set; }
        public Item Bow { get; set; }
        public Item Bow4 { get; set; }
        public Item Bowofthedead { get; set; }
        public Item Bronzeingot { get; set; }
        public Item Bronzenugget { get; set; }
        public Item Brownegg { get; set; }
        public Item Btusk { get; set; }
        public Item Bugbountybox { get; set; }
        public Item Bunnyears { get; set; }
        public Item Bunnyelixir { get; set; }
        public Item Bwing { get; set; }
        public Item Cake { get; set; }
        public Item Candy0 { get; set; }
        public Item Candy0V2 { get; set; }
        public Item Candy0V3 { get; set; }
        public Item Candy1 { get; set; }
        public Item Candy1V2 { get; set; }
        public Item Candy1V3 { get; set; }
        public Item Candycane { get; set; }
        public Item Candycanesword { get; set; }
        public Item Candypop { get; set; }
        public Item Cape { get; set; }
        public Item Carrot { get; set; }
        public Item Carrotsword { get; set; }
        public Item Cclaw { get; set; }
        public Item Cdarktristone { get; set; }
        public Item Cdragon { get; set; }
        public Item Cearring { get; set; }
        public Item Charmer { get; set; }
        public Item Chrysalis0 { get; set; }
        public Item Claw { get; set; }
        public Item Coal { get; set; }
        public Item Coat { get; set; }
        public Item Coat1 { get; set; }
        public Item Cocoon { get; set; }
        public Item Computer { get; set; }
        public Item Confetti { get; set; }
        public Item Cosmo0 { get; set; }
        public Item Cosmo1 { get; set; }
        public Item Cosmo2 { get; set; }
        public Item Cosmo3 { get; set; }
        public Item Cosmo4 { get; set; }
        public Item Crabclaw { get; set; }
        public Item Cring { get; set; }
        public Item Critscroll { get; set; }
        public Item Crossbow { get; set; }
        public Item Cryptkey { get; set; }
        public Item Cscale { get; set; }
        public Item Cscroll0 { get; set; }
        public Item Cscroll1 { get; set; }
        public Item Cscroll2 { get; set; }
        public Item Cscroll3 { get; set; }
        public Item Cshell { get; set; }
        public Item Ctristone { get; set; }
        public Item Cupid { get; set; }
        public Item Cxjar { get; set; }
        public Item Cyber { get; set; }
        public Item Dagger { get; set; }
        public Item Daggerofthedead { get; set; }
        public Item Darktristone { get; set; }
        public Item Dartgun { get; set; }
        public Item Dexamulet { get; set; }
        public Item Dexbelt { get; set; }
        public Item Dexearring { get; set; }
        public Item Dexearringx { get; set; }
        public Item Dexring { get; set; }
        public Item Dexscroll { get; set; }
        public Item Dkey { get; set; }
        public Item Dragondagger { get; set; }
        public Item Drapes { get; set; }
        public Item Dreturnscroll { get; set; }
        public Item Dstones { get; set; }
        public Item Ecape { get; set; }
        public Item Ectoplasm { get; set; }
        public Item Eears { get; set; }
        public Item Egg0 { get; set; }
        public Item Egg1 { get; set; }
        public Item Egg2 { get; set; }
        public Item Egg3 { get; set; }
        public Item Egg4 { get; set; }
        public Item Egg5 { get; set; }
        public Item Egg6 { get; set; }
        public Item Egg7 { get; set; }
        public Item Egg8 { get; set; }
        public Item Eggnog { get; set; }
        public Item Electronics { get; set; }
        public Item Elixirdex0 { get; set; }
        public Item Elixirdex1 { get; set; }
        public Item Elixirdex2 { get; set; }
        public Item Elixirfires { get; set; }
        public Item Elixirfzres { get; set; }
        public Item Elixirint0 { get; set; }
        public Item Elixirint1 { get; set; }
        public Item Elixirint2 { get; set; }
        public Item Elixirluck { get; set; }
        public Item Elixirpnres { get; set; }
        public Item Elixirstr0 { get; set; }
        public Item Elixirstr1 { get; set; }
        public Item Elixirstr2 { get; set; }
        public Item Elixirvit0 { get; set; }
        public Item Elixirvit1 { get; set; }
        public Item Elixirvit2 { get; set; }
        public Item Emotionjar { get; set; }
        public Item Emptyheart { get; set; }
        public Item Emptyjar { get; set; }
        public Item Epyjamas { get; set; }
        public Item Eslippers { get; set; }
        public Item Espresso { get; set; }
        public Item Essenceofether { get; set; }
        public Item Essenceoffire { get; set; }
        public Item Essenceoffrost { get; set; }
        public Item Essenceofgreed { get; set; }
        public Item Essenceoflife { get; set; }
        public Item Essenceofnature { get; set; }
        public Item Evasionscroll { get; set; }
        public Item Exoarm { get; set; }
        public Item Fallen { get; set; }
        public Item Fcape { get; set; }
        public Item Fclaw { get; set; }
        public Item Feather0 { get; set; }
        public Item Fieldgen0 { get; set; }
        public Item Fierygloves { get; set; }
        public Item Figurine { get; set; }
        public Item Fireblade { get; set; }
        public Item Firebow { get; set; }
        public Item Firecrackers { get; set; }
        public Item Firestaff { get; set; }
        public Item Firestars { get; set; }
        public Item Flute { get; set; }
        public Item Forscroll { get; set; }
        public Item Frankypants { get; set; }
        public Item Frequencyscroll { get; set; }
        public Item Frogt { get; set; }
        public Item Frostbow { get; set; }
        public Item Froststaff { get; set; }
        public Item Frozenkey { get; set; }
        public Item Frozenstone { get; set; }
        public Item Fsword { get; set; }
        public Item Ftrinket { get; set; }
        public Item Funtoken { get; set; }
        public Item Fury { get; set; }
        public Item Gbow { get; set; }
        public Item Gcape { get; set; }
        public Item Gem0 { get; set; }
        public Item Gem1 { get; set; }
        public Item Gem2 { get; set; }
        public Item Gem3 { get; set; }
        public Item Gemfragment { get; set; }
        public Item Ghatb { get; set; }
        public Item Ghatp { get; set; }
        public Item Gift0 { get; set; }
        public Item Gift1 { get; set; }
        public Item Glitch { get; set; }
        public Item Gloves { get; set; }
        public Item Gloves1 { get; set; }
        public Item Goldbooster { get; set; }
        public Item Goldenegg { get; set; }
        public Item Goldenpowerglove { get; set; }
        public Item Goldingot { get; set; }
        public Item Goldnugget { get; set; }
        public Item Goldring { get; set; }
        public Item Goldscroll { get; set; }
        public Item Gphelmet { get; set; }
        public Item Greenbomb { get; set; }
        public Item Greenenvelope { get; set; }
        public Item Gslime { get; set; }
        public Item Gstaff { get; set; }
        public Item Gum { get; set; }
        public Item Hammer { get; set; }
        public Item Handofmidas { get; set; }
        public Item Harbringer { get; set; }
        public Item Harmor { get; set; }
        public Item Hboots { get; set; }
        public Item Hbow { get; set; }
        public Item Hdagger { get; set; }
        public Item Heartwood { get; set; }
        public Item Helmet { get; set; }
        public Item Helmet1 { get; set; }
        public Item Hgloves { get; set; }
        public Item Hhelmet { get; set; }
        public Item Hotchocolate { get; set; }
        public Item Hpamulet { get; set; }
        public Item Hpants { get; set; }
        public Item Hpbelt { get; set; }
        public Item Hpot0 { get; set; }
        public Item Hpot1 { get; set; }
        public Item Hpotx { get; set; }
        public Item Iceskates { get; set; }
        public Item Ijx { get; set; }
        public Item Ink { get; set; }
        public Item Intamulet { get; set; }
        public Item Intbelt { get; set; }
        public Item Intearring { get; set; }
        public Item Intring { get; set; }
        public Item Intscroll { get; set; }
        public Item Jacko { get; set; }
        public Item Jewellerybox { get; set; }
        public Item Kitty1 { get; set; }
        public Item Lantern { get; set; }
        public Item Lbelt { get; set; }
        public Item Leather { get; set; }
        public Item Ledger { get; set; }
        public Item Licence { get; set; }
        public Item Lifestealscroll { get; set; }
        public Item Lmace { get; set; }
        public Item Lostearring { get; set; }
        public Item Lotusf { get; set; }
        public Item Lspores { get; set; }
        public Item Luckbooster { get; set; }
        public Item Luckscroll { get; set; }
        public Item Luckyt { get; set; }
        public Item Mace { get; set; }
        public Item Maceofthedead { get; set; }
        public Item Mageshood { get; set; }
        public Item Manastealscroll { get; set; }
        public Item Mbelt { get; set; }
        public Item Mbones { get; set; }
        public Item Mcape { get; set; }
        public Item Mcarmor { get; set; }
        public Item Mcboots { get; set; }
        public Item Mcgloves { get; set; }
        public Item Mchat { get; set; }
        public Item Mcpants { get; set; }
        public Item Mearring { get; set; }
        public Item Merry { get; set; }
        public Item Mistletoe { get; set; }
        public Item Mittens { get; set; }
        public Item Mmarmor { get; set; }
        public Item Mmgloves { get; set; }
        public Item Mmhat { get; set; }
        public Item Mmpants { get; set; }
        public Item Mmshoes { get; set; }
        public Item Molesteeth { get; set; }
        public Item Monsterbox { get; set; }
        public Item Monstertoken { get; set; }
        public Item Mparmor { get; set; }
        public Item Mpcostscroll { get; set; }
        public Item Mpgloves { get; set; }
        public Item Mphat { get; set; }
        public Item Mpot0 { get; set; }
        public Item Mpot1 { get; set; }
        public Item Mpotx { get; set; }
        public Item Mppants { get; set; }
        public Item Mpshoes { get; set; }
        public Item Mpxamulet { get; set; }
        public Item Mpxbelt { get; set; }
        public Item Mpxgloves { get; set; }
        public Item Mrarmor { get; set; }
        public Item Mrboots { get; set; }
        public Item Mrgloves { get; set; }
        public Item Mrhood { get; set; }
        public Item Mrnarmor { get; set; }
        public Item Mrnboots { get; set; }
        public Item Mrngloves { get; set; }
        public Item Mrnhat { get; set; }
        public Item Mrnpants { get; set; }
        public Item Mrpants { get; set; }
        public Item Mshield { get; set; }
        public Item Mushroomstaff { get; set; }
        public Item Mwarmor { get; set; }
        public Item Mwboots { get; set; }
        public Item Mwgloves { get; set; }
        public Item Mwhelmet { get; set; }
        public Item Mwpants { get; set; }
        public Item Mysterybox { get; set; }
        public Item Networkcard { get; set; }
        public Item Nheart { get; set; }
        public Item Northstar { get; set; }
        public Item Offering { get; set; }
        public Item Offeringp { get; set; }
        public Item Offeringx { get; set; }
        public Item Oozingterror { get; set; }
        public Item Orbg { get; set; }
        public Item Orbofdex { get; set; }
        public Item Orbofint { get; set; }
        public Item Orbofsc { get; set; }
        public Item Orbofstr { get; set; }
        public Item Orbofvit { get; set; }
        public Item Ornament { get; set; }
        public Item Ornamentstaff { get; set; }
        public Item Outputscroll { get; set; }
        public Item Oxhelmet { get; set; }
        public Item Pants { get; set; }
        public Item Pants1 { get; set; }
        public Item Partyhat { get; set; }
        public Item Phelmet { get; set; }
        public Item Pickaxe { get; set; }
        public Item Pico { get; set; }
        public Item Pinkie { get; set; }
        public Item Placeholder { get; set; }

        [JsonProperty("placeholder_m")]
        public Item PlaceholderM { get; set; }

        public Item Platinumingot { get; set; }
        public Item Platinumnugget { get; set; }
        public Item Pleather { get; set; }
        public Item Pmace { get; set; }
        public Item Poison { get; set; }
        public Item Poker { get; set; }
        public Item Pouchbow { get; set; }
        public Item Powerglove { get; set; }
        public Item Pstem { get; set; }
        public Item Pumpkinspice { get; set; }
        public Item Puppy1 { get; set; }
        public Item Puppyer { get; set; }
        public Item Pvptoken { get; set; }
        public Item Pyjamas { get; set; }
        public Item Qubics { get; set; }
        public Item Quiver { get; set; }
        public Item Rabbitsfoot { get; set; }
        public Item Rapier { get; set; }
        public Item Rattail { get; set; }
        public Item Redenvelope { get; set; }
        public Item Redenvelopev2 { get; set; }
        public Item Redenvelopev3 { get; set; }
        public Item Rednose { get; set; }
        public Item Reflectionscroll { get; set; }
        public Item Resistancering { get; set; }
        public Item Resistancescroll { get; set; }
        public Item Rfangs { get; set; }
        public Item Rfur { get; set; }
        public Item Ringofluck { get; set; }
        public Item Ringsj { get; set; }
        public Item Rod { get; set; }
        public Item Rpiercingscroll { get; set; }
        public Item Sanguine { get; set; }
        public Item Santasbelt { get; set; }
        public Item Scroll0 { get; set; }
        public Item Scroll1 { get; set; }
        public Item Scroll2 { get; set; }
        public Item Scroll3 { get; set; }
        public Item Scroll4 { get; set; }
        public Item Scythe { get; set; }
        public Item Seashell { get; set; }
        public Item Shadowstone { get; set; }
        public Item Shield { get; set; }
        public Item Shoes { get; set; }
        public Item Shoes1 { get; set; }
        public Item Slimestaff { get; set; }
        public Item Smoke { get; set; }
        public Item Smush { get; set; }
        public Item Snakefang { get; set; }
        public Item Snakeoil { get; set; }
        public Item Snowball { get; set; }
        public Item Snowboots { get; set; }
        public Item Snowflakes { get; set; }
        public Item Snring { get; set; }
        public Item Solitaire { get; set; }
        public Item Spear { get; set; }
        public Item Spearofthedead { get; set; }
        public Item Speedscroll { get; set; }
        public Item Spidersilk { get; set; }
        public Item Spores { get; set; }
        public Item Sshield { get; set; }
        public Item Sstinger { get; set; }
        public Item Staff { get; set; }
        public Item Staff2 { get; set; }
        public Item Staff3 { get; set; }
        public Item Staff4 { get; set; }
        public Item Staffofthedead { get; set; }
        public Item Stand0 { get; set; }
        public Item Stand1 { get; set; }
        public Item Starkillers { get; set; }
        public Item Stealthcape { get; set; }
        public Item Stick { get; set; }
        public Item Stinger { get; set; }
        public Item Stonekey { get; set; }
        public Item Stoneofgold { get; set; }
        public Item Stoneofluck { get; set; }
        public Item Stoneofxp { get; set; }
        public Item Storagebox { get; set; }
        public Item Stramulet { get; set; }
        public Item Strbelt { get; set; }
        public Item Strearring { get; set; }
        public Item Strring { get; set; }
        public Item Strscroll { get; set; }
        public Item Suckerpunch { get; set; }
        public Item Supermittens { get; set; }
        public Item Svenom { get; set; }
        public Item Swifty { get; set; }
        public Item Swirlipop { get; set; }
        public Item Sword { get; set; }
        public Item Swordofthedead { get; set; }
        public Item T2Bow { get; set; }
        public Item T2dexamulet { get; set; }
        public Item T2Intamulet { get; set; }
        public Item T2Quiver { get; set; }
        public Item T2Stramulet { get; set; }
        public Item T3Bow { get; set; }
        public Item Talkingskull { get; set; }
        public Item Test { get; set; }
        public Item Test2 { get; set; }

        [JsonProperty("test_orb")]
        public Item TestOrb { get; set; }

        public Item Throwingstars { get; set; }
        public Item Tombkey { get; set; }
        public Item Tracker { get; set; }
        public Item Trigger { get; set; }
        public Item Trinkets { get; set; }
        public Item Tristone { get; set; }
        public Item Troll { get; set; }
        public Item Tshell { get; set; }
        public Item Tshirt0 { get; set; }
        public Item Tshirt1 { get; set; }
        public Item Tshirt2 { get; set; }
        public Item Tshirt3 { get; set; }
        public Item Tshirt4 { get; set; }
        public Item Tshirt6 { get; set; }
        public Item Tshirt7 { get; set; }
        public Item Tshirt8 { get; set; }
        public Item Tshirt88 { get; set; }
        public Item Tshirt9 { get; set; }
        public Item Ukey { get; set; }
        public Item Vattire { get; set; }
        public Item Vblood { get; set; }
        public Item Vboots { get; set; }
        public Item Vcape { get; set; }
        public Item Vdagger { get; set; }
        public Item Vgloves { get; set; }
        public Item Vhammer { get; set; }
        public Item Vitearring { get; set; }
        public Item Vitring { get; set; }
        public Item Vitscroll { get; set; }
        public Item Vorb { get; set; }
        public Item Vring { get; set; }
        public Item Vstaff { get; set; }
        public Item Vsword { get; set; }
        public Item Wand { get; set; }
        public Item Warmscarf { get; set; }
        public Item Warpvest { get; set; }
        public Item Watercore { get; set; }
        public Item Wattire { get; set; }
        public Item Wbasher { get; set; }
        public Item Wblade { get; set; }
        public Item Wbook0 { get; set; }
        public Item Wbook1 { get; set; }
        public Item Wbreeches { get; set; }
        public Item Wcap { get; set; }
        public Item Weaponbox { get; set; }
        public Item Weaver { get; set; }
        public Item Wgloves { get; set; }
        public Item Whiskey { get; set; }
        public Item Whiteegg { get; set; }
        public Item Wine { get; set; }
        public Item Wingedboots { get; set; }
        public Item Woodensword { get; set; }
        public Item Wshield { get; set; }
        public Item Wshoes { get; set; }
        public Item X0 { get; set; }
        public Item X1 { get; set; }
        public Item X2 { get; set; }
        public Item X3 { get; set; }
        public Item X4 { get; set; }
        public Item X5 { get; set; }
        public Item X6 { get; set; }
        public Item X7 { get; set; }
        public Item X8 { get; set; }
        public Item Xarmor { get; set; }
        public Item Xboots { get; set; }
        public Item Xbox { get; set; }
        public Item Xgloves { get; set; }
        public Item Xhelmet { get; set; }
        public Item Xmace { get; set; }
        public Item Xmashat { get; set; }
        public Item Xmaspants { get; set; }
        public Item Xmasshoes { get; set; }
        public Item Xmassweater { get; set; }
        public Item Xpants { get; set; }
        public Item Xpbooster { get; set; }
        public Item Xpscroll { get; set; }
        public Item Xptome { get; set; }
        public Item Xshield { get; set; }
        public Item Xshot { get; set; }
        public Item Zapper { get; set; }
    }
}