#region
using System.Text.Json.Nodes;
using System.Text.Json.Serialization;
using AL.Core.Definitions;
#endregion

namespace AL.SocketClient.SocketModel;

/// <summary>
///     Represents the data received when initially joining a server.
/// </summary>
/// <seealso cref="CharacterData" />
public class StartData : CharacterData
{
    /// <summary>
    ///     A collection of values indicating base gold rewards for killing a monster on a specific map.
    ///     <br />
    ///     These values are dynamically generated by the server, and different based on class, level, and other factors.
    ///     <br />
    ///     { MonsterName : { MapName: GoldValue } }
    /// </summary>
    [JsonPropertyName("base_gold")]
    public IReadOnlyDictionary<string, IReadOnlyDictionary<string, int>> BaseGold { get; init; }
        = new Dictionary<string, IReadOnlyDictionary<string, int>>();

    /// <summary>
    ///     If the server is blessed, the character name of the patron who blessed it.
    /// </summary>
    [JsonPropertyName("blessed_by")]
    public string? BlessedBy { get; init; }

    /// <summary>
    ///     If the server is blessed, the minutes of blessing remaining.
    /// </summary>
    [JsonPropertyName("blessed_minutes")]
    public int BlessedMinutes { get; init; }

    /// <summary>
    ///     If code is running for this character, the slot it is loaded in. Sent as a string.
    /// </summary>
    [JsonPropertyName("code_slot")]
    public string? CodeSlot { get; init; }

    /// <summary>
    ///     If code is running for this character, its version number.
    /// </summary>
    [JsonPropertyName("code_version")]
    public int CodeVersion { get; init; }

    /// <summary>
    ///     The emotions this character has unlocked and their unlock timestamps.
    /// </summary>
    /// <remarks>
    ///     Start-only: sent as <c>emx</c> on join and never on a <c>player</c> frame.
    /// </remarks>
    [JsonPropertyName("emx")]
    public IReadOnlyDictionary<Emotion, float> Emotion { get; init; } = new Dictionary<Emotion, float>();

    /// <summary>Initial entity load for the map you loaded into.</summary>
    public EntitiesData Entities { get; init; } = null!;

    /// <summary>
    ///     Contains data for ongoing events and bosses for this server.
    /// </summary>
    /// <remarks>
    ///     Must stay typed as <see cref="EventAndBossData" />: its converter, the only thing that fills <c>BossInfo</c>, does
    ///     not claim a base-typed member, and every boss would be dropped.
    /// </remarks>
    [JsonPropertyName("s_info")]
    public EventAndBossData EventAndBossInfo { get; init; } = null!;

    /// <summary>
    ///     The names of this character's exclusive (class-locked) cosmetics.
    /// </summary>
    /// <remarks>
    ///     Start-only: sent as <c>xcx</c> on join. A flat string list, unlike the <c>acx</c> dictionary in
    ///     <see cref="OwnedCosmetics" />.
    /// </remarks>
    [JsonPropertyName("xcx")]
    public IReadOnlyList<string> ExclusiveCosmetics { get; init; } = new List<string>();

    /// <summary>
    ///     The names of the characters on this account's friends list.
    /// </summary>
    /// <remarks>
    ///     Start-only: sent as <c>friends</c> on join and never on a <c>player</c> frame.
    /// </remarks>
    [JsonPropertyName("friends")]
    public IReadOnlyList<string> Friends { get; init; } = new List<string>();

    /// <summary>
    ///     The server this character calls home, as <c>region + server_name</c>. Start-only; a successful <c>set_home</c>
    ///     reports the new home through the <c>home_set</c> game response.
    /// </summary>
    [JsonPropertyName("home")]
    public string? Home { get; init; }

    /// <summary>
    ///     A short-lived token used to re-authenticate to the API without the password.
    /// </summary>
    /// <remarks>
    ///     Start-only: sent as <c>ipass</c> on join and never on a <c>player</c> frame.
    /// </remarks>
    [JsonPropertyName("ipass")]

    // ReSharper disable once InconsistentNaming
    public string? IPass { get; init; }

    /// <summary>
    ///     The current instance's info blob. Shape depends on the instance type (e.g. duel state); defaults to an empty
    ///     object.
    /// </summary>
    /// <remarks>Start-only: sent as <c>info</c> on join.</remarks>
    [JsonPropertyName("info")]
    public JsonObject? InstanceInfo { get; init; }

    /// <summary>
    ///     A collection of all of the cosmetics owned by this character.
    /// </summary>
    /// <remarks>
    ///     Start-only: sent as <c>acx</c> on join and never on a <c>player</c> frame.
    /// </remarks>
    [JsonPropertyName("acx")]
    public IReadOnlyDictionary<string, int> OwnedCosmetics { get; init; } = new Dictionary<string, int>();
}