<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\AL.APIClient\AL.APIClient.csproj"/>
        <ProjectReference Include="..\AL.Data\AL.Data.csproj"/>
    </ItemGroup>

</Project>