<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <Title>AL.SocketClient</Title>
        <Description>SocketClient library for the ALClientCS project. Builds off an existing socket.io implementation with fully asynchronous socket handling. Maps out socket calls sent and received to the Adventure.Land socket server.</Description>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\AL.APIClient\AL.APIClient.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="SocketIO.Serializer.SystemTextJson" Version="3.1.2"/>
        <PackageReference Include="SocketIOClient" Version="3.1.2"/>
    </ItemGroup>

</Project>
