<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <Title>AL.Client</Title>
        <Description>A headless client for the Adventure.Land game.</Description>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\AL.Data\AL.Data.csproj"/>
        <ProjectReference Include="..\AL.Pathfinding\AL.Pathfinding.csproj"/>
        <ProjectReference Include="..\AL.SocketClient\AL.SocketClient.csproj"/>
    </ItemGroup>

</Project>
