#region
using System.Text.Json.Nodes;
using AL.Core.Definitions;
using FluentAssertions;
#endregion

namespace AL.Tests.Characterization;

/// <summary>
///     Pins the outbound wire form of every member of the six emit-reachable enums. The committed snapshot is the fixed
///     target; the live side is the production System.Text.Json emit path the socket transport uses. A regression to
///     integer serialization is the exact failure that has already destroyed inventory once:
///     <see cref="TradeSlot.Trade1" /> is 17, so
///     <c>
///         {"slot":17}
///     </c>
///     is a plausible value the server acts on where
///     <c>
///         {"slot":"trade1"}
///     </c>
///     is intended.
/// </summary>
/// <remarks>
///     The full name-to-wire map is committed as a snapshot generated by enumerating <see cref="Enum.GetNames{T}" />; a
///     member added to (or removed from) any of the six enums breaks
///     <see cref="T7_EnumWireForms_StjPath_ReproducesCommittedSnapshot" /> because the live enumeration no longer matches
///     the committed set.
/// </remarks>
public class EmitEnumWireFormCharacterization
{
    private const string SNAPSHOT_NAME = "enum-wire-forms.json";

    private static void AssertRoundTrips<T>() where T: struct, Enum
    {
        foreach (var name in Enum.GetNames<T>())
        {
            var value = Enum.Parse<T>(name);

            //both halves go through the production options: emitting with default options turns TradeSlot.Trade1
            //into 17 rather than "trade1", which would make this assert a round-trip the server never sees
            var bare = TestJson.Emit(value);

            TestJson.Socket<T>(bare)
                    .Should()
                    .Be(value, $"{typeof(T).Name}.{name} did not round-trip from {bare}.");
        }
    }

    private static JsonObject BuildLiveMap()
        => new()
        {
            ["Slot"] = WireMap<Slot>(),
            ["TradeSlot"] = WireMap<TradeSlot>(),
            ["BankPack"] = WireMap<BankPack>(),
            ["Stand"] = WireMap<Stand>(),
            ["ALClass"] = WireMap<ALClass>(),
            ["WeaponType"] = WireMap<WeaponType>()
        };

    private static string CollapseThrow(string? wireForm)
        => wireForm is null
            ? "<missing>"
            : wireForm.StartsWith("<<throws:", StringComparison.Ordinal)
                ? "<<throws>>"
                : wireForm;

    /// <summary>
    ///     Every (enum, member, position) cell whose wire form differs between the two maps, plus every cell the live map has
    ///     and the committed one does not.
    /// </summary>
    /// <remarks>
    ///     The two inbound-only enums (<see cref="Stand" />, <see cref="ALClass" />) refuse to emit under both engines, but
    ///     name different exception types for it — the snapshot was pinned when their converters threw
    ///     <c>
    ///         NotImplementedException
    ///     </c>
    ///     from an unimplemented
    ///     <c>
    ///         WriteJson
    ///     </c>
    ///     ; the System.Text.Json converters throw
    ///     <c>
    ///         NotSupportedException
    ///     </c>
    ///     . Which exception a refusal carries is not a wire form, so both collapse to one sentinel here; a refusal turning
    ///     into an actual emitted value (or the reverse) still differs and still fails, which is the property that matters.
    /// </remarks>
    private static List<string> DifferingCells(JsonObject committed, JsonObject live)
    {
        var differences = new List<string>();

        foreach ((var enumName, var members) in committed)
            foreach ((var memberName, var forms) in (JsonObject)members!)
                foreach (var position in new[]
                         {
                             "bare",
                             "inObject"
                         })
                {
                    var expected = CollapseThrow(forms![position]!.GetValue<string>());

                    var actual = CollapseThrow(
                        live[enumName]?[memberName]?[position]
                            ?.GetValue<string>());

                    if (expected != actual)
                        differences.Add($"{enumName}.{memberName}.{position}: committed={expected} live={actual}");
                }

        //the walk above only visits cells the snapshot already has, so a member added to an enum since it was
        //pinned would otherwise reach the wire unpinned - the removal direction is covered above as <missing>
        foreach ((var enumName, var members) in live)
            foreach ((var memberName, _) in (JsonObject)members!)
                if (committed[enumName]?[memberName] is null)
                    differences.Add($"{enumName}.{memberName}: emitted live, absent from the committed snapshot");

        return differences;
    }

    /// <summary>
    ///     Serializes a value, recording the exception type instead of the wire string when emit throws. Two of the six enums
    ///     (<see cref="Stand" />, <see cref="ALClass" />) are inbound-only: their converters refuse to write, so emit throws
    ///     rather than producing a string.
    /// </summary>
    private static string SerializeOrSentinel(Func<string> serialize)
    {
        try
        {
            return serialize();
        } catch (Exception ex)
        {
            var inner = ex.InnerException is null ? string.Empty : $" -> {ex.InnerException.GetType().FullName}";

            return $"<<throws:{ex.GetType().FullName}{inner}>>";
        }
    }

    [Test]
    public void T7_ALClass_DeserializesFromWireForm()
    {
        TestJson.Socket<ALClass>(@"""mage""")
                .Should()
                .Be(ALClass.Mage);

        TestJson.Socket<ALClass>(@"""merchant""")
                .Should()
                .Be(ALClass.Merchant);

        TestJson.Socket<ALClass>(@"""warrior""")
                .Should()
                .Be(ALClass.Warrior);

        //null degrades to the zero member
        TestJson.Socket<ALClass>("null")
                .Should()
                .Be(ALClass.None);
    }

    [Test]
    public void T7_ALClass_Emit_Throws()
    {
        //ALClassConverter.Write refuses; ALClass is an inbound-only field and is never emitted
        FluentActions.Invoking(() => TestJson.Emit(ALClass.Mage))
                     .Should()
                     .ThrowExactly<NotSupportedException>();

        FluentActions.Invoking(() => TestJson.Emit(
                         new Box<ALClass>
                         {
                             V = ALClass.Mage
                         }))
                     .Should()
                     .ThrowExactly<NotSupportedException>();
    }

    [Test]
    public void T7_ALClass_UnknownValue_DegradesToNpc_NotZero()
    {
        //ALClassConverter is the one exception: an unrecognized class becomes NPC (8), not the zero member None -
        //the server treats an unknown entity as an NPC, so this is deliberate, but it breaks the "degrades to
        //zero" invariant the other five enums hold
        TestJson.Socket<ALClass>(@"""nonexistent_class""")
                .Should()
                .Be(ALClass.NPC);

        TestJson.Socket<ALClass>(@"""nonexistent_class""")
                .Should()
                .NotBe(ALClass.None);
    }

    /// <summary>
    ///     The migration's proof for T7: every emit-reachable enum member must reach the wire under the production
    ///     System.Text.Json options exactly as the pinned snapshot says it does, and no member may be added, removed, renamed,
    ///     or re-shaped without this failing.
    /// </summary>
    [Test]
    public void T7_EnumWireForms_StjPath_ReproducesCommittedSnapshot()
    {
        var committedText = Fixture.ReadCommittedSnapshot(SNAPSHOT_NAME);

        committedText.Should()
                     .NotBeNull($"Committed snapshot \"{SNAPSHOT_NAME}\" is missing.");

        var committed = JsonNode.Parse(committedText)!.AsObject();
        var live = BuildLiveMap();

        var differences = DifferingCells(committed, live);

        differences.Count
                   .Should()
                   .Be(0, $"System.Text.Json emit diverges from the pinned wire forms:\n{string.Join("\n", differences)}");
    }

    [Test]
    public void T7_Stand_DeserializesFromLowercaseWireForm()
    {
        //the server sends the lowercase member name; the FalsyConverter matches it case-insensitively
        TestJson.Socket<Stand>(@"""stand""")
                .Should()
                .Be(Stand.Stand);

        TestJson.Socket<Stand>(@"""cstand""")
                .Should()
                .Be(Stand.CStand);

        TestJson.Socket<Stand>(@"""stand0""")
                .Should()
                .Be(Stand.Stand0);

        TestJson.Socket<Stand>(@"""stand1""")
                .Should()
                .Be(Stand.Stand1);

        //"false" (the falsy wire form) degrades to the default
        TestJson.Socket<Stand>("false")
                .Should()
                .Be(Stand.None);
    }

    [Test]
    public void T7_Stand_Emit_Throws()
    {
        //FalsyConverter<Stand>.Write refuses; Stand is an inbound-only field and is never emitted
        FluentActions.Invoking(() => TestJson.Emit(Stand.Stand))
                     .Should()
                     .ThrowExactly<NotSupportedException>();

        FluentActions.Invoking(() => TestJson.Emit(
                         new Box<Stand>
                         {
                             V = Stand.Stand
                         }))
                     .Should()
                     .ThrowExactly<NotSupportedException>();
    }

    [Test]
    public void T7_StringEnums_DeserializeBackFromEveryEmittedWireForm()
    {
        //round-trip: every member that emits a string must deserialize back to itself
        AssertRoundTrips<Slot>();
        AssertRoundTrips<TradeSlot>();
        AssertRoundTrips<BankPack>();
        AssertRoundTrips<WeaponType>();
    }

    [Test]
    public void T7_UnknownValue_DegradesToZeroMember()
    {
        //the tolerant converter defaults an unrecognized wire value to the enum's zero member rather than throwing
        TestJson.Socket<Slot>(@"""nonexistent_slot""")
                .Should()
                .Be(Slot.None);

        TestJson.Socket<TradeSlot>(@"""nonexistent_slot""")
                .Should()
                .Be(TradeSlot.None);

        TestJson.Socket<BankPack>(@"""nonexistent_pack""")
                .Should()
                .Be(BankPack.None);

        TestJson.Socket<WeaponType>(@"""nonexistent_weapon""")
                .Should()
                .Be(WeaponType.None);

        TestJson.Socket<Stand>(@"""nonexistent_stand""")
                .Should()
                .Be(Stand.None);
    }

    /// <summary>
    ///     name -> {bare, inObject} for every declared member of an enum, in ascending value order.
    /// </summary>
    private static JsonObject WireMap<T>() where T: struct, Enum
    {
        var map = new JsonObject();

        foreach (var name in Enum.GetNames<T>())
        {
            var value = Enum.Parse<T>(name);

            //TestJson.Emit, never an inline Serialize: it carries the options the transport actually emits with
            var bare = SerializeOrSentinel(() => TestJson.Emit(value));

            var inObject = SerializeOrSentinel(() => TestJson.Emit(
                new Box<T>
                {
                    V = value
                }));

            map[name] = new JsonObject
            {
                ["bare"] = bare,
                ["inObject"] = inObject
            };
        }

        return map;
    }

    /// <summary>
    ///     Wraps an enum so it is serialized in object-property-value position rather than as a bare value.
    /// </summary>
    private sealed class Box<T>
    {
        // ReSharper disable once UnusedAutoPropertyAccessor.Local
        public T V { get; init; } = default!;
    }
}