#region
using System;
using System.Collections.Generic;
using AL.Core.Definitions;
using AL.Core.Json;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using StjSerializer = System.Text.Json.JsonSerializer;
#endregion

namespace AL.Tests.Characterization;

/// <summary>
///     Pins the outbound wire form of every member of the six emit-reachable enums under Newtonsoft, so the
///     System.Text.Json migration has a fixed target. A regression to integer serialization is the exact
///     failure that has already destroyed inventory once: <see cref="TradeSlot.Trade1" /> is 17, so
///     <c>{"slot":17}</c> is a plausible value the server acts on where <c>{"slot":"trade1"}</c> is intended.
/// </summary>
/// <remarks>
///     The full name-to-wire map is committed as a snapshot generated by enumerating
///     <see cref="Enum.GetNames{T}" />; a member added later to any of the six enums breaks
///     <see cref="T7_EnumWireForms_MatchCommittedSnapshot" /> because the live enumeration no longer matches
///     the committed set.
/// </remarks>
[TestClass]
public class EmitEnumWireFormCharacterization
{
    private const string SNAPSHOT_NAME = "enum-wire-forms.json";

    //property name in the object-position wrapper; kept short and deterministic so the wire form is stable
    private const string BOX_PROPERTY = "V";

    /// <summary>
    ///     Wraps an enum so it is serialized in object-property-value position rather than as a bare value.
    /// </summary>
    private sealed class Box<T>
    {
        public T V { get; init; } = default!;
    }

    /// <summary>
    ///     Serializes a value, recording the exception type instead of the wire string when emit throws. Two of
    ///     the six enums (<see cref="Stand" />, <see cref="ALClass" />) are inbound-only: their converters leave
    ///     WriteJson unimplemented, so emit throws rather than producing a string.
    /// </summary>
    private static string SerializeOrSentinel(Func<string> serialize)
    {
        try
        {
            return serialize();
        } catch (Exception ex)
        {
            var inner = ex.InnerException is null ? string.Empty : $" -> {ex.InnerException.GetType().FullName}";

            return $"<<throws:{ex.GetType().FullName}{inner}>>";
        }
    }

    /// <summary>
    ///     name -> {bare, inObject} for every declared member of an enum, in ascending value order.
    /// </summary>
    private static JObject WireMap<T>(bool useStj) where T: struct, Enum
    {
        var map = new JObject();

        foreach (var name in Enum.GetNames<T>())
        {
            var value = Enum.Parse<T>(name);

            var bare = SerializeOrSentinel(
                () => useStj ? StjSerializer.Serialize(value, ALJson.Options) : JsonConvert.SerializeObject(value));

            var inObject = SerializeOrSentinel(
                () => useStj
                    ? StjSerializer.Serialize(new Box<T> { V = value }, ALJson.Options)
                    : JsonConvert.SerializeObject(new Box<T> { V = value }));

            map[name] = new JObject
            {
                ["bare"] = bare,
                ["inObject"] = inObject
            };
        }

        return map;
    }

    private static JObject BuildLiveMap(bool useStj)
        => new()
        {
            ["Slot"] = WireMap<Slot>(useStj),
            ["TradeSlot"] = WireMap<TradeSlot>(useStj),
            ["BankPack"] = WireMap<BankPack>(useStj),
            ["Stand"] = WireMap<Stand>(useStj),
            ["ALClass"] = WireMap<ALClass>(useStj),
            ["WeaponType"] = WireMap<WeaponType>(useStj)
        };

    /// <summary>
    ///     Every (enum, member, position) cell whose wire form differs between the two maps.
    /// </summary>
    /// <remarks>
    ///     The two inbound-only enums (<see cref="Stand" />, <see cref="ALClass" />) refuse to emit under both
    ///     engines, but name different exception types for it — Newtonsoft's converter throws
    ///     <c>NotImplementedException</c> from its unimplemented <c>WriteJson</c>, System.Text.Json's throws
    ///     <c>NotSupportedException</c>. Which exception a refusal carries is not a wire form, so both collapse
    ///     to one sentinel here; a refusal turning into an actual emitted value (or the reverse) still differs
    ///     and still fails, which is the property that matters.
    /// </remarks>
    private static List<string> DifferingCells(JObject newtonsoft, JObject stj)
    {
        var differences = new List<string>();

        foreach (var (enumName, members) in newtonsoft)
        foreach (var (memberName, forms) in (JObject)members!)
        foreach (var position in new[] { "bare", "inObject" })
        {
            var expected = CollapseThrow((string)forms![position]!);
            var actual = CollapseThrow((string?)stj[enumName]?[memberName]?[position]);

            if (expected != actual)
                differences.Add($"{enumName}.{memberName}.{position}: newtonsoft={expected} stj={actual}");
        }

        return differences;
    }

    private static string CollapseThrow(string? wireForm)
        => wireForm is null ? "<missing>" :
            wireForm.StartsWith("<<throws:", StringComparison.Ordinal) ? "<<throws>>" : wireForm;

    [TestMethod]
    public void T7_EnumWireForms_MatchCommittedSnapshot()
    {
        var live = BuildLiveMap(useStj: false);
        var committedText = Fixture.ReadCommittedSnapshot(SNAPSHOT_NAME);

        if (committedText is null)
        {
            //sidecar name, never the committed one - see AttributesCensusCharacterization for why
            var generatedPath = Fixture.WriteSnapshot($"{SNAPSHOT_NAME}.generated", live.ToString(Formatting.Indented));

            Assert.Fail(
                $"Committed snapshot \"{SNAPSHOT_NAME}\" is missing. Generated it at {generatedPath}; copy it to "
                + "AL.Tests/Fixtures/snapshots/ and re-run so the build copies it back.");
        }

        var committed = JObject.Parse(committedText!);

        //DeepEquals fails if any member was added, removed, renamed, or changed its wire form - which is the
        //whole point: no enum member can drift without this test noticing
        Assert.IsTrue(
            JToken.DeepEquals(committed, live),
            $"Live enum wire forms differ from the committed snapshot.\nCommitted:\n{committed.ToString(Formatting.Indented)}\n\nLive:\n{live.ToString(Formatting.Indented)}");
    }

    /// <summary>
    ///     The migration's proof for T7: every emit-reachable enum member must reach the wire the same way under
    ///     the production System.Text.Json options as it does under the pinned Newtonsoft snapshot.
    /// </summary>
    [TestMethod]
    public void T7_EnumWireForms_StjPath_ReproducesCommittedSnapshot()
    {
        var committedText = Fixture.ReadCommittedSnapshot(SNAPSHOT_NAME);

        Assert.IsNotNull(committedText, $"Committed snapshot \"{SNAPSHOT_NAME}\" is missing.");

        var committed = JObject.Parse(committedText);
        var stj = BuildLiveMap(useStj: true);

        var differences = DifferingCells(committed, stj);

        Assert.AreEqual(
            0,
            differences.Count,
            $"System.Text.Json emit diverges from the pinned Newtonsoft wire forms:\n{string.Join("\n", differences)}");
    }

    [TestMethod]
    public void T7_TradeSlot_Trade1_EmitsQuotedStringNotSeventeen()
    {
        //the destructive regression: TradeSlot.Trade1 == 17, so a slip to integer emit yields {"slot":17},
        //a value the server acts on - it previously consumed the item instead of listing it
        var bare = JsonConvert.SerializeObject(TradeSlot.Trade1);

        Assert.AreEqual(@"""trade1""", bare);
        Assert.AreNotEqual("17", bare);
        Assert.AreEqual(JTokenType.String, JToken.Parse(bare).Type);
    }

    [TestMethod]
    public void T7_EveryStringEnumMember_EmitsAJsonStringNeverAnInteger()
    {
        //guards the entire failure class, not just Trade1: no member of the four emit-capable enums may
        //serialize to a bare number in either position
        AssertAllMembersEmitStrings<Slot>();
        AssertAllMembersEmitStrings<TradeSlot>();
        AssertAllMembersEmitStrings<BankPack>();
        AssertAllMembersEmitStrings<WeaponType>();
    }

    private static void AssertAllMembersEmitStrings<T>() where T: struct, Enum
    {
        foreach (var name in Enum.GetNames<T>())
        {
            var value = Enum.Parse<T>(name);
            var bare = JsonConvert.SerializeObject(value);
            var inObject = JsonConvert.SerializeObject(new Box<T> { V = value });

            Assert.AreEqual(JTokenType.String, JToken.Parse(bare).Type, $"{typeof(T).Name}.{name} bare emit is not a JSON string.");
            Assert.AreEqual(
                JTokenType.String,
                JToken.Parse(inObject)[BOX_PROPERTY]!.Type,
                $"{typeof(T).Name}.{name} in-object emit is not a JSON string.");
        }
    }

    [TestMethod]
    public void T7_Slot_EmitsLowercaseName_BareAndInObject()
    {
        Assert.AreEqual(@"""none""", JsonConvert.SerializeObject(Slot.None));
        Assert.AreEqual(@"""mainhand""", JsonConvert.SerializeObject(Slot.MainHand));
        Assert.AreEqual(@"""offhand""", JsonConvert.SerializeObject(Slot.OffHand));
        Assert.AreEqual(@"""ring1""", JsonConvert.SerializeObject(Slot.Ring1));
        Assert.AreEqual(@"""trade1""", JsonConvert.SerializeObject(Slot.Trade1));
        Assert.AreEqual(@"""trade30""", JsonConvert.SerializeObject(Slot.Trade30));

        Assert.AreEqual(@"{""V"":""mainhand""}", JsonConvert.SerializeObject(new Box<Slot> { V = Slot.MainHand }));
        Assert.AreEqual(@"{""V"":""trade1""}", JsonConvert.SerializeObject(new Box<Slot> { V = Slot.Trade1 }));
    }

    [TestMethod]
    public void T7_TradeSlot_EmitsLowercaseName_BareAndInObject()
    {
        Assert.AreEqual(@"""none""", JsonConvert.SerializeObject(TradeSlot.None));
        Assert.AreEqual(@"""trade1""", JsonConvert.SerializeObject(TradeSlot.Trade1));
        Assert.AreEqual(@"""trade30""", JsonConvert.SerializeObject(TradeSlot.Trade30));

        Assert.AreEqual(@"{""V"":""trade1""}", JsonConvert.SerializeObject(new Box<TradeSlot> { V = TradeSlot.Trade1 }));
        Assert.AreEqual(@"{""V"":""trade30""}", JsonConvert.SerializeObject(new Box<TradeSlot> { V = TradeSlot.Trade30 }));
    }

    [TestMethod]
    public void T7_BankPack_EmitsLowercaseName_BareAndInObject()
    {
        Assert.AreEqual(@"""none""", JsonConvert.SerializeObject(BankPack.None));
        Assert.AreEqual(@"""items0""", JsonConvert.SerializeObject(BankPack.Items0));
        Assert.AreEqual(@"""items47""", JsonConvert.SerializeObject(BankPack.Items47));

        Assert.AreEqual(@"{""V"":""items0""}", JsonConvert.SerializeObject(new Box<BankPack> { V = BankPack.Items0 }));
    }

    [TestMethod]
    public void T7_WeaponType_EmitsMemberNameHonoringEnumMember_BareAndInObject()
    {
        //no naming strategy here, so the wire form is the CLR name, except where [EnumMember] overrides it
        Assert.AreEqual(@"""None""", JsonConvert.SerializeObject(WeaponType.None));
        Assert.AreEqual(@"""Axe""", JsonConvert.SerializeObject(WeaponType.Axe));
        Assert.AreEqual(@"""great_staff""", JsonConvert.SerializeObject(WeaponType.GreatStaff));
        Assert.AreEqual(@"""great_sword""", JsonConvert.SerializeObject(WeaponType.GreatSword));
        Assert.AreEqual(@"""misc_offhand""", JsonConvert.SerializeObject(WeaponType.MiscOffhand));
        Assert.AreEqual(@"""short_sword""", JsonConvert.SerializeObject(WeaponType.ShortSword));

        Assert.AreEqual(@"{""V"":""Axe""}", JsonConvert.SerializeObject(new Box<WeaponType> { V = WeaponType.Axe }));
        Assert.AreEqual(@"{""V"":""great_staff""}", JsonConvert.SerializeObject(new Box<WeaponType> { V = WeaponType.GreatStaff }));
    }

    [TestMethod]
    public void T7_Stand_Emit_Throws()
    {
        //FalsyConverter<Stand>.WriteJson is unimplemented; Stand is an inbound-only field and is never emitted
        Assert.ThrowsException<NotImplementedException>(() => JsonConvert.SerializeObject(Stand.Stand));
        Assert.ThrowsException<NotImplementedException>(() => JsonConvert.SerializeObject(new Box<Stand> { V = Stand.Stand }));
    }

    [TestMethod]
    public void T7_ALClass_Emit_Throws()
    {
        //ALClassConverter.WriteJson is unimplemented; ALClass is an inbound-only field and is never emitted
        Assert.ThrowsException<NotImplementedException>(() => JsonConvert.SerializeObject(ALClass.Mage));
        Assert.ThrowsException<NotImplementedException>(() => JsonConvert.SerializeObject(new Box<ALClass> { V = ALClass.Mage }));
    }

    [TestMethod]
    public void T7_StringEnums_DeserializeBackFromEveryEmittedWireForm()
    {
        //round-trip: every member that emits a string must deserialize back to itself
        AssertRoundTrips<Slot>();
        AssertRoundTrips<TradeSlot>();
        AssertRoundTrips<BankPack>();
        AssertRoundTrips<WeaponType>();
    }

    private static void AssertRoundTrips<T>() where T: struct, Enum
    {
        foreach (var name in Enum.GetNames<T>())
        {
            var value = Enum.Parse<T>(name);
            var bare = JsonConvert.SerializeObject(value);

            Assert.AreEqual(value, JsonConvert.DeserializeObject<T>(bare), $"{typeof(T).Name}.{name} did not round-trip from {bare}.");
        }
    }

    [TestMethod]
    public void T7_Stand_DeserializesFromLowercaseWireForm()
    {
        //the server sends the lowercase member name; the FalsyConverter matches it case-insensitively
        Assert.AreEqual(Stand.Stand, JsonConvert.DeserializeObject<Stand>(@"""stand"""));
        Assert.AreEqual(Stand.CStand, JsonConvert.DeserializeObject<Stand>(@"""cstand"""));
        Assert.AreEqual(Stand.Stand0, JsonConvert.DeserializeObject<Stand>(@"""stand0"""));
        Assert.AreEqual(Stand.Stand1, JsonConvert.DeserializeObject<Stand>(@"""stand1"""));

        //"false" (the falsy wire form) degrades to the default
        Assert.AreEqual(Stand.None, JsonConvert.DeserializeObject<Stand>("false"));
    }

    [TestMethod]
    public void T7_ALClass_DeserializesFromWireForm()
    {
        Assert.AreEqual(ALClass.Mage, JsonConvert.DeserializeObject<ALClass>(@"""mage"""));
        Assert.AreEqual(ALClass.Merchant, JsonConvert.DeserializeObject<ALClass>(@"""merchant"""));
        Assert.AreEqual(ALClass.Warrior, JsonConvert.DeserializeObject<ALClass>(@"""warrior"""));

        //null degrades to the zero member
        Assert.AreEqual(ALClass.None, JsonConvert.DeserializeObject<ALClass>("null"));
    }

    [TestMethod]
    public void T7_UnknownValue_DegradesToZeroMember()
    {
        //the tolerant converter defaults an unrecognized wire value to the enum's zero member rather than throwing
        Assert.AreEqual(Slot.None, JsonConvert.DeserializeObject<Slot>(@"""nonexistent_slot"""));
        Assert.AreEqual(TradeSlot.None, JsonConvert.DeserializeObject<TradeSlot>(@"""nonexistent_slot"""));
        Assert.AreEqual(BankPack.None, JsonConvert.DeserializeObject<BankPack>(@"""nonexistent_pack"""));
        Assert.AreEqual(WeaponType.None, JsonConvert.DeserializeObject<WeaponType>(@"""nonexistent_weapon"""));
        Assert.AreEqual(Stand.None, JsonConvert.DeserializeObject<Stand>(@"""nonexistent_stand"""));
    }

    [TestMethod]
    public void T7_ALClass_UnknownValue_DegradesToNpc_NotZero()
    {
        //ALClassConverter is the one exception: an unrecognized class becomes NPC (8), not the zero member None -
        //the server treats an unknown entity as an NPC, so this is deliberate, but it breaks the "degrades to
        //zero" invariant the other five enums hold
        Assert.AreEqual(ALClass.NPC, JsonConvert.DeserializeObject<ALClass>(@"""nonexistent_class"""));
        Assert.AreNotEqual(ALClass.None, JsonConvert.DeserializeObject<ALClass>(@"""nonexistent_class"""));
    }
}
